// incantesimi.js
// Database degli incantesimi/trucchetti conoscibili, organizzati per categoria.
// "modificatore" indica quale caratteristica il manuale richiede per quell'incantesimo
// (informativo: il sistema usa comunque la caratteristica incantatore più alta del personaggio).

window.DATABASE_INCANTESIMI = {
    danni: [
        {
            nome: "Arma Magica",
            livello: 2,
            modificatore: ["Intelligenza"],
            azione: "Azione bonus",
            raggio: "A contatto",
            durata: "10 minuti",
            concentrazione: true,
            desc: "Tocchi un'arma non magica. Finché l'incantesimo non termina, quell'arma diventa un'arma magica con un bonus di +1 ai tiri per colpire e ai tiri per i danni.",
            effetto: { tipo: 'buff_arma', bonus: 1, durataOre: 1 },
            cd: false,
            tiro_abilita: false
        },
        {
            nome: "Arma Spirituale",
            livello: 2,
            modificatore: ["Intelligenza", "Saggezza"],
            azione: "Azione bonus",
            raggio: "18 metri",
            durata: "1 minuto",
            concentrazione: false,
            desc: "Crei un'arma spettrale fluttuante entro il raggio d'azione che dura per la durata dell'incantesimo o finché non lo lanci di nuovo. Quando lanci l'incantesimo, puoi effettuare un attacco con incantesimo in mischia contro una creatura entro 1,5 metri dall'arma. Se colpisci, il bersaglio subisce danni da forza pari a 1d8 + il tuo modificatore di caratteristica da incantatore. Come azione bonus nel tuo turno, puoi spostare l'arma fino a 6 metri e ripetere l'attacco contro una creatura entro 1,5 metri da essa. L'arma può assumere qualsiasi forma tu scelga.",
            effetto: { tipo: 'evocazione_attacco', danno: '1d8', dannoTipo: 'forza', raggioMetri: 18, durataTurni: 10 },
            cd: false,
            tiro_abilita: true
        },
        {
            nome:"Armatura di Agathys",
            livello:1,
            modificatore:["Saggezza","Carisma"],
            azione:"Azione",
            raggio:"Su se stesso",
            durata:"2 minuti",
            concentrazione: false,
            desc:"Una forza magica protettiva ti circonda, manifestandosi come un gelo spettrale che ricopre te e il tuo equipaggiamento. Ottieni 5 punti ferita temporanei per la durata. Se una creatura ti colpisce con un attacco in mischia mentre hai questi punti ferita, la creatura subisce 2 danni da freddo.",
            effetto:{tipo:'armatura_agathys', pfTemp:5, danno:'5', dannoTipo:'freddo'},
            cd:false,
            tiro_abilita:false
        },
        {
            nome:"Blocca persone",
            livello:2,
            modificatore:["Carisma","Saggezza"],
            azione:"Azione",
            durata:"1 minuto",
            concentrazione: true,
            desc:"Scegli un umanoide che puoi vedere entro il raggio d'azione. Il bersaglio deve superare un tiro salvezza su Saggezza o rimanere paralizzato per la durata dell'incantesimo. Alla fine di ogni suo turno, il bersaglio può effettuare un altro tiro salvezza su Saggezza. In caso di successo, l'incantesimo termina sul bersaglio.",
            effetto:{tipo:'blocca_persone', ts:'Saggezza', durataTurni:10},
            cd:true,
            tiro_abilita:false
        },
        {
            nome: "Cecità/Sordità",
            livello: 2,
            modificatore: ["Saggezza", "Carisma"],
            azione: "Azione",
            raggio: "9 metri",
            durata: "1 minuto",
            concentrazione: false,
            desc: "Puoi accecare o assordare un nemico. Scegli una creatura che puoi vedere entro il raggio d'azione per effettuare un tiro salvezza su Costituzione. Se fallisce, il bersaglio è accecato o assordato (a tua scelta) per la durata dell'incantesimo. Alla fine di ogni suo turno, il bersaglio può effettuare un tiro salvezza su Costituzione. In caso di successo, l'incantesimo termina.",
            effetto: { tipo: 'ts_debuff', ts: 'Costituzione', condizione: 'accecato_assordato', durataTurni: 10 },
            cd: true,
            tiro_abilita: false
        },
        {
            nome: "Dardo di Fuoco",
            livello: 0,
            modificatore: ["Qualsiasi"],
            azione: "Azione",
            raggio: "9 metri",
            durata: "Istantanea",
            concentrazione: false,
            desc: "Lanci una particella di fuoco contro una creatura o un oggetto entro la gittata. Attacco con incantesimo a distanza: se colpisci, 1d10 danni da fuoco. Un oggetto infiammabile non indossato/trasportato prende fuoco.",
            effetto: { tipo: 'attacco_distanza', danno: '1d10', dannoTipo: 'fuoco' },
            cd: false,
            tiro_abilita:true
        },
        {
            nome: "Detonazione Psionica",
            livello: 3,
            modificatore: ["Intelligenza"],
            azione: "Azione",
            raggio: "Se stesso (cono di 9 metri)",
            durata: "Istantanea",
            concentrazione: false,
            desc: "Scateni un'onda distruttiva di potere mentale in un cono di 9 metri. Ogni creatura nell'area deve effettuare un tiro salvezza su Destrezza. Se fallisce, subisce 5d8 danni da forza, viene spinta di 6 metri in linea retta lontano da te e cade prona. Se ha successo, subisce la metà dei danni e non viene spinta né fatta cadere prona.",
            effetto: { tipo: 'ts_danno_spinta', ts: 'Destrezza', danno: '5d8', dannoTipo: 'forza', spintaMetri: 6, prono: true },
            cd: true,
            tiro_abilita: false
        },
        {
            nome:"Esca fulminante",
            livello:0,
            modificatore:["Saggezza"],
            azione:"Azione",
            raggio:"4.5 metri",
            durata:"Istantanea",
            concentrazione: false,
            desc:"Crei una scarica di energia fulminea che colpisce una creatura a tua scelta che puoi vedere entro 4,5 metri da te. Il bersaglio deve superare un tiro salvezza su Forza o essere trascinato fino a 3 metri in linea retta verso di te e subire 1d8 danni da fulmine se si trova entro 1,5 metri da te.",
            effetto:{tipo:'ts_danno', ts:'Forza', danno:'1d8', dannoTipo:'fulmine'},
            cd:true,
            tiro_abilita:false
        },
        {
            nome: "Falsa Vita",
            livello: 1,
            modificatore: ["Intelligenza", "Carisma"],
            azione: "Azione",
            raggio: "Se stesso",
            durata: "1 ora",
            concentrazione: false,
            desc: "Rafforzandoti con una simulazione necromantica della vita, ottieni 1d4 + 4 punti ferita temporanei per la durata dell'incantesimo.",
            effetto: { tipo: 'buff_pf_temp', pfTemp: '1d4+4', durataOre: 1 },
            cd: false,
            tiro_abilita: false
        },
          {
            nome:"Fiamma sacra",
            livello:0,
            modificatore:["Saggezza"],
            azione:"Azione",
            raggio:"12 metri",
            durata:"Istantanea",
            concentrazione:false,
            desc:"Un bagliore simile a una fiamma si abbatte su una creatura che puoi vedere entro il raggio d'azione. Il bersaglio deve superare un tiro salvezza su Destrezza o subire 1d8 danni radianti. Il bersaglio non ottiene alcun beneficio dalla copertura per questo tiro salvezza.",
            effetto:{tipo:'fiamma_sacra', durataOre: 1},
            cd:true,
            tiro_abilita:false
        },
        {
            nome: "Fiotto Acido",
            livello: 0,
            modificatore: ["Intelligenza", "Saggezza"],
            azione: "Azione",
            raggio:"12 metri",
            durata: "Istantanea",
            concentrazione: false,
            desc: "Lanci una bolla di acido. Scegli una creatura che puoi vedere entro il raggio d'azione, oppure due creature entro 1,5 metri l'una dall'altra. Un bersaglio deve superare un TS su Destrezza o subire 1d6 danni da acido.",
            effetto: { tipo: 'ts_danno', ts: 'Destrezza', danno: '1d6', dannoTipo: 'acido' },
            cd: true,
            tiro_abilita:true
        },
        {
            nome: "Fulmine",
            livello: 3,
            modificatore: ["Intelligenza"],
            azione: "Azione",
            raggio: "Se stesso (linea di 30 metri)",
            durata: "Istantanea",
            concentrazione: false,
            desc: "Un raggio di fulmine che forma una linea lunga 30 metri e larga 1,5 metri scaturisce da te in una direzione a tua scelta. Ogni creatura nella linea deve effettuare un tiro salvezza su Destrezza. Una creatura subisce 8d6 danni da fulmine se fallisce il tiro salvezza, o la metà di questi danni se lo supera. Il fulmine incendia gli oggetti infiammabili nell'area che non sono indossati o trasportati.",
            effetto: { tipo: 'ts_danno', ts: 'Destrezza', danno: '8d6', dannoTipo: 'fulmine' },
            cd: true,
            tiro_abilita: false
        },
        {
            nome: "Ghiaccio Vincolante di Rime",
            livello: 2,
            modificatore: ["Intelligenza"],
            azione: "Azione",
            raggio: "Se stesso (cono di 9 metri)",
            durata: "Istantanea",
            concentrazione: false,
            desc: "Un'esplosione di energia gelida emana da te in un cono di 9 metri. Ogni creatura in quell'area deve effettuare un tiro salvezza su Costituzione. Se fallisce, la creatura subisce 3d8 danni da freddo ed è ostacolata da formazioni di ghiaccio per 1 minuto, o finché essa o un'altra creatura a portata non usa un'azione per rompere il ghiaccio. Una creatura ostacolata dal ghiaccio ha la sua velocità ridotta a 0. Se ha successo, la creatura subisce la metà dei danni e non è ostacolata dal ghiaccio.",
            effetto: { tipo: 'ts_danno_controllo', ts: 'Costituzione', danno: '3d8', dannoTipo: 'freddo', condizione: 'velocita_zero', durataTurni: 10 },
            cd: true,
            tiro_abilita: false
        },
        {   nome: "Illusione minore",
            livello : 0,
            modificatore: ["Intelligenza"],
            azione: "Azione",
            raggio: "9 metri",
            durata: "1 minuto",
            concentrazione:false,
            desc:"Crei un suono o un'immagine di un oggetto entro il raggio d'azione che dura per tutta la durata dell'incantesimo. L'illusione termina anche se la annulli con un'azione o se lanci nuovamente questo incantesimo. \n Se crei un suono, il suo volume può variare da un sussurro a un urlo. Può essere la tua voce, la voce di qualcun altro, il ruggito di un leone, il suono di un tamburo o qualsiasi altro suono tu scelga. Il suono continua ininterrottamente per tutta la durata dell'incantesimo, oppure puoi emettere suoni distinti in momenti diversi prima che l'incantesimo termini. \n Se crei l'immagine di un oggetto, questa non deve essere più grande di un cubo di 1,5 metri di lato. L'immagine non può creare suoni, luce, odori o altri effetti sensoriali. L'interazione fisica con l'immagine rivela che si tratta di un'illusione, perché gli oggetti possono attraversarla. \n Se una creatura usa la sua azione per esaminare il suono o l'immagine, può determinare che si tratta di un'illusione con una prova di Intelligenza (Indagine) contro la CD del tuo tiro salvezza. Se una creatura discerne l'illusione per quello che è, l'illusione diventa debole per la creatura.",
            effetto:{tipo:'illusione_minore', durataTurni:10},
            cd:true,
            tiro_abilita:false
        },
        {
            nome:"Infestazione",
            livello:0,
            modificatore:["Saggezza","Carisma"],
            azione:"Azione",
            raggio:"6 metri",
            durata:"Istantanea",
            concentrazione: false,
            desc:"Provochi una nuvola di acari, pulci e altri parassiti che appaiono momentaneamente su una creatura che puoi vedere entro il raggio d'azione. Il bersaglio deve superare un tiro salvezza su Costituzione, altrimenti subisce 1d6 danni da veleno e si muove di 1,5 metri in una direzione casuale se può muoversi e la sua velocità è di almeno 1,5 metri. Tira un d4 per la direzione: 1, nord; 2, sud; 3, est; o 4, ovest. Questo movimento non provoca attacchi di opportunità e, se la direzione indicata è bloccata, il bersaglio non si muove.",
            effetto:{tipo:'ts_danno', ts:'Costituzione', danno:'1d6', dannoTipo:'veleno'},
            cd:true,
            tiro_abilita:false
        },
        {
            nome: "Lama Infuocata",
            livello: 2,
            modificatore: ["Carisma"],
            azione: "Azione bonus",
            raggio: "Se stesso",
            durata: "10 minuti",
            concentrazione: true,
            desc: "Evochi una lama di fuoco nella tua mano libera. La lama è simile per dimensioni e forma a una scimitarra e dura per la durata dell'incantesimo. Se lasci andare la lama, scompare, ma puoi evocarla di nuovo come azione bonus. Puoi usare la tua azione per effettuare un attacco con incantesimo in mischia con la lama di fuoco. Se colpisci, il bersaglio subisce 3d6 danni da fuoco. La lama infuocata emette luce intensa in un raggio di 3 metri e luce fioca per altri 3 metri.",
            effetto: { tipo: 'arma_evocata', danno: '3d6', dannoTipo: 'fuoco', durataTurni: 100 },
            cd: false,
            tiro_abilita: true
        },
        {
            nome:"Lama tonante",
            livello:0,
            modificatore:["Qualsiasi"],
            azione:"Azione",
            durata:"1 turno",
            concentrazione: false,
            desc:"Impugna l'arma usata per lanciare l'incantesimo ed effettua un attacco in mischia contro una creatura entro 1,5 metri da te. In caso di successo, il bersaglio subisce gli effetti normali dell'attacco con l'arma e viene avvolto da un'energia rimbombante fino all'inizio del tuo prossimo turno. Se il bersaglio si muove volontariamente di 1,5 metri o più prima di allora, subisce 1d8 danni da tuono e l'incantesimo termina.",
            effetto:{tipo:'attacco_mischia',danno:'1d8',dannoTipo:'tuono'},
            cd:false,
            tiro_abilita:false

        },
        {
            nome: "Mano di Carte",
            livello: 2,
            modificatore: ["Carisma"],
            azione: "Azione",
            raggio: "Cono di 4,5 metri",
            durata: "Istantanea",
            concentrazione: false,
            desc: "Spruzzi carte spettrali dalle tue mani o dalle maniche; le carte accecano o tagliano i tuoi nemici, per poi svanire. Scegli uno dei seguenti effetti: \n - Carte Accecanti: Ogni creatura in un cono di 4,5 metri deve superare un tiro salvezza su Saggezza o essere accecata fino alla fine del suo prossimo turno. \n - Carte Taglienti: Ogni creatura in un cono di 4,5 metri deve effettuare un tiro salvezza su Destrezza. Subisce 2d10 danni da forza se fallisce, o la metà se ha successo.",
            effetto: { tipo: 'scelta_ts', ts1: 'Saggezza', ts2: 'Destrezza', danno: '2d10', dannoTipo: 'forza', condizione: 'accecato' },
            cd: true,
            tiro_abilita: false
        },
        {
            nome:"Mano radiante",
            livello:0,
            modificatore:["Carisma"],
            azione:"Azione",
            raggio:"1.5 metri",
            durata:"Istantanea",
            desc:"Alzi la mano e da essa erutta una luce ardente. Ogni creatura a tua scelta che puoi vedere entro 1,5 metri da te deve superare un tiro salvezza su Costituzione o subire 1d6 danni radianti.",
            effetto:{tipo:'ts_danno', ts:'Costituzione', danno:'1d6', dannoTipo:'radianti'},
            cd:true,
            tiro_abilita:false
        },
        {
            nome:"Morsa congelante",
            livello:0,
            modificatore:["Intelligenza","Saggezza"],
            azione:"Azione",
            raggio:"9 metri",
            durata:"Istantanea",
            concentrazione: false,
            desc:"Provochi una gelata paralizzante su una creatura che puoi vedere entro il raggio d'azione. Il bersaglio deve effettuare un tiro salvezza su Costituzione. In caso di fallimento, il bersaglio subisce 1d6 danni da freddo e ha svantaggio al prossimo tiro per colpire con un'arma che effettua prima della fine del suo prossimo turno.",
            effetto:{tipo:'ts_danno', ts:'Costituzione', danno:'1d6', dannoTipo:'freddo'},
            cd:true,
            tiro_abilita:false

        },
        {
            nome:"Nebbia",
            livello:1,
            modificatore:["Intelligenza","Saggezza"],
            azione:"Azione",
            raggio:"9 metri",
            durata:"5 minuti",
            concentrazione: true,
            desc:"Si crea una sfera di nebbia con un raggio di 6 metri centrata su un punto entro il raggio d'azione. La sfera si espande attorno agli angoli e la sua area è fortemente oscurata. Dura per tutta la durata dell'effetto o finché un vento di velocità moderata o superiore (almeno 8 km/h) non la disperde.",
            effetto:{tipo:'nebbia', raggioMetri:6, durataTurni:50},
            cd:false,
            tiro_abilita:false
        },
        {
            nome: "Nube di Pugnali",
            livello: 2,
            modificatore: ["Intelligenza"],
            azione: "Azione",
            raggio: "18 metri",
            durata: "1 minuto",
            concentrazione: true,
            desc: "Riempi l'aria di pugnali rotanti in un cubo di 1,5 metri di lato, centrato su un punto a tua scelta entro il raggio d'azione. Una creatura subisce 4d4 danni taglienti quando entra nell'area dell'incantesimo per la prima volta in un turno o quando vi inizia il suo turno.",
            effetto: { tipo: 'area_danno', danno: '4d4', dannoTipo: 'taglienti', areaMetri: 1.5, durataTurni: 10 },
            cd: false,
            tiro_abilita: false
        },
        {
            nome: "Oscurità",
            livello: 2,
            modificatore: ["Carisma"],
            azione: "Azione",
            raggio: "18 metri",
            durata: "10 minuti",
            concentrazione: true,
            desc: "L'oscurità magica si diffonde da un punto a tua scelta entro il raggio d'azione per riempire una sfera di 4,5 metri di raggio. L'oscurità si diffonde dietro gli angoli. Una creatura con scurovisione non può vedere attraverso di essa e la luce non magica non può illuminarla. Se il punto è su un oggetto che tieni in mano o non indossato, l'oscurità si muove con esso. Coprire la fonte con un oggetto opaco blocca l'oscurità. Se si sovrappone a luce creata da un incantesimo di livello 2 o inferiore, quell'incantesimo di luce viene dissolto.",
            effetto: { tipo: 'oscurita', raggioMetri: 4.5, durataTurni: 100 },
            cd: false,
            tiro_abilita: false
        },
        {
            nome:"Passi cinetici",
            livello:2,
            modificatore:["Carisma"],
            azione:"Azione bonus",
            raggio:"Se stesso",
            durata:"1 minuto",
            concentrazione: true,
            desc:"Potenzia magicamente i tuoi movimenti con passi di danza, ottenendo i seguenti benefici per la durata: \n -La tua velocità di movimento aumenta di 3 metri. \n -Non provochi attacchi di opportunità. \n -Puoi muoverti attraverso lo spazio di un'altra creatura e non conta come terreno difficile. Se termini il tuo turno nello spazio di un'altra creatura, vieni spostato nell'ultimo spazio libero che hai occupato e subisci 1d8 danni da forza.",
            effetto:{tipo:'Moviento potenziato'},
            cd:false,
            tiro_abilita:false
        },
        {
            nome: "Pelle di Corteccia",
            livello: 2,
            modificatore: ["Saggezza"],
            azione: "Azione",
            raggio: "A contatto",
            durata: "10 minuti",
            concentrazione: true,
            desc: "Tocchi una creatura consenziente. Finché l'incantesimo non termina, la pelle del bersaglio ha un aspetto ruvido, simile alla corteccia, e la sua CA non può essere inferiore a 16, indipendentemente dal tipo di armatura che indossa.",
            effetto: { tipo: 'buff_ca', caMinima: 16, durataTurni: 100 },
            cd: false,
            tiro_abilita: false
        },
        {
            nome: "Pirotecnica",
            livello: 2,
            modificatore: ["Carisma"],
            azione: "Azione",
            raggio: "18 metri",
            durata: "Istantanea",
            concentrazione: false,
            desc: "Scegli un'area di fiamma che puoi vedere e che possa entrare in un cubo di 1,5 metri entro il raggio d'azione. Puoi spegnere il fuoco in quell'area e creare fuochi d'artificio o fumo. \n - Fuochi d'artificio: Il bersaglio esplode in uno sfolgorante spettacolo di colori. Ogni creatura entro 3 metri dal bersaglio deve superare un tiro salvezza su Costituzione o essere accecata fino alla fine del tuo prossimo turno. \n - Fumo: Un denso fumo nero si diffonde dal bersaglio in un raggio di 6 metri, espandendosi oltre gli angoli. L'area del fumo è fortemente oscurata. Il fumo persiste per 1 minuto o finché un forte vento non lo disperde.",
            effetto: { tipo: 'pirotecnica', ts: 'Costituzione', condizione: 'accecato', raggioFumoMetri: 6, durataTurni: 10 },
            cd: true,
            tiro_abilita: false
        },
        {
            nome:"Puntura abbatente",
            livello:0,
            modificatore:["Intelligenza","Carisma"],
            azione:"Azione",
            raggio:"6 metri",
            durata:"Istantanea",
            concentrazione: false,
            desc:"Assorbi la vitalità di una creatura che puoi vedere entro il raggio d'azione. Il bersaglio deve superare un tiro salvezza su Costituzione o subire 1d4 danni necrotici e cadere prono.",
            effetto:{tipo:'ts_danno', ts:'Costituzione', danno:'1d4', dannoTipo:'necrotici'},
            cd:true,
            tiro_abilita:false
        },
        {
            nome: "Raggio di Indebolimento",
            livello: 2,
            modificatore: ["Intelligenza","Carisma"],
            azione: "Azione",
            raggio: "18 metri",
            durata: "1 minuto",
            concentrazione: true,
            desc: "Un raggio nero di energia snervante scaturisce dal tuo dito verso una creatura entro il raggio d'azione. Effettua un attacco con incantesimo a distanza contro il bersaglio. Se colpisci, il bersaglio infligge solo la metà dei danni con gli attacchi con armi che usano la Forza finché l'incantesimo non termina. Alla fine di ogni suo turno, il bersaglio può effettuare un tiro salvezza su Costituzione contro l'incantesimo. In caso di successo, l'incantesimo termina.",
            effetto: { tipo: 'debuff_danno', ts: 'Costituzione', durataTurni: 10 },
            cd: true,
            tiro_abilita: true
        },
        {
            nome: "Raggio Rovente",
            livello: 2,
            modificatore: ["Intelligenza"],
            azione: "Azione",
            raggio: "36 metri",
            durata: "Istantanea",
            concentrazione: false,
            desc: "Crei tre raggi di fuoco e li scagli contro bersagli entro il raggio d'azione. Puoi scagliarli contro un singolo bersaglio o bersagli multipli. Effettua un attacco con incantesimo a distanza per ogni raggio. Se colpisci, il bersaglio subisce 2d6 danni da fuoco.",
            effetto: { tipo: 'attacco_distanza_multiplo', raggi: 3, danno: '2d6', dannoTipo: 'fuoco' },
            cd: false,
            tiro_abilita: true
        },
        {
            nome: "Ragnatela",
            livello: 2,
            modificatore: ["Saggezza"],
            azione: "Azione",
            raggio: "9 metri",
            durata: "10 minuti",
            concentrazione: true,
            desc: "Evochi una massa di ragnatele spesse e appiccicose in un punto a tua scelta entro il raggio d'azione. Le ragnatele riempiono un cubo di 6 metri per la durata dell'incantesimo. Le ragnatele sono terreno difficile e oscurano leggermente l'area. Se le ragnatele non sono ancorate tra due masse solide o stratificate su un pavimento, parete o soffitto, collassano e l'incantesimo termina all'inizio del tuo prossimo turno. Ogni creatura che inizia il suo turno nelle ragnatele o ci entra deve effettuare un tiro salvezza su Destrezza. Se fallisce, è trattenuta. Come azione, può effettuare una prova di Forza contro la CD dell'incantesimo per liberarsi. Le ragnatele sono infiammabili: un cubo di 1,5 metri brucia in 1 round infliggendo 2d4 danni da fuoco a chiunque vi inizi il turno.",
            effetto: { tipo: 'area_controllo', ts: 'Destrezza', condizione: 'trattenuto', areaMetri: 6, durataTurni: 100 },
            cd: true,
            tiro_abilita: false
        },
        {
            nome: "Risveglio Primordiale",
            livello: 0,
            modificatore: ["Saggezza"],
            azione: "Azione",
            raggio: "1,5 metri",
            durata: "Istantanea",
            concentrazione: false,
            desc: "Incanali la magia primordiale per affilare denti o unghie. Attacco magico in mischia (1,5m): se colpisci, il bersaglio subisce 1d10 danni da acido. Dopo l'attacco, torni alla normalità.",
            effetto: { tipo: 'attacco_mischia', danno: '1d10', dannoTipo: 'acido' },
            cd: false,
            tiro_abilita:true
        },
        {
            nome: "Sfocatura",
            livello: 2,
            modificatore: ["Intelligenza", "Saggezza"],
            azione: "Azione",
            raggio: "Se stesso",
            durata: "1 minuto",
            concentrazione: true,
            desc: "Il tuo corpo diventa sfocato, alterandosi e ondeggiando agli occhi di chiunque possa vederti. Per la durata dell'incantesimo, qualsiasi creatura ha svantaggio ai tiri per colpire contro di te. Un attaccante è immune a questo effetto se non fa affidamento sulla vista, come con la vista cieca, o se può vedere attraverso le illusioni, come con la vista autentica.",
            effetto: { tipo: 'sfocatura', durataTurni: 10 },
            cd: false,
            tiro_abilita: false
        },
        {
            nome: "Sfera Infuocata",
            livello: 2,
            modificatore: ["Carisma","Sggezza"],
            azione: "Azione",
            raggio: "18 metri",
            durata: "1 minuto",
            concentrazione: true,
            desc: "Una sfera di fuoco del diametro di 1,5 metri appare in uno spazio libero a tua scelta entro il raggio d'azione e dura per la durata dell'incantesimo. Qualsiasi creatura che termini il suo turno entro 1,5 metri dalla sfera deve effettuare un tiro salvezza su Destrezza. La creatura subisce 2d6 danni da fuoco se fallisce il tiro salvezza, o la metà di questi danni se lo supera. Come azione bonus, puoi spostare la sfera fino a 9 metri. Se fai scontrare la sfera con una creatura, questa deve effettuare il tiro salvezza contro i danni della sfera, e la sfera smette di muoversi per questo turno. Quando muovi la sfera, puoi dirigerla oltre barriere alte fino a 1,5 metri e farle saltare fosse larghe fino a 3 metri. La sfera incendia gli oggetti infiammabili non indossati o trasportati ed emette luce intensa in un raggio di 6 metri e luce fioca per altri 6 metri.",
            effetto: { tipo: 'area_danno_mobile', ts: 'Destrezza', danno: '2d6', dannoTipo: 'fuoco', durataTurni: 10 },
            cd: true,
            tiro_abilita: false
        },
        {
            nome: "Sigillo di Protezione",
            livello: 0,
            modificatore: ["Intelligenza"],
            azione: "1 Azione",
            raggio: "Su se stesso",
            durata: "1 turno",
            concentrazione: true,
            desc: "Estendi la mano e tracci un sigillo di protezione nell'aria. Fino alla fine del tuo prossimo turno, hai resistenza al prossimo danno contundente, perforante o tagliente inflitto dagli attacchi con armi.",
            effetto: { tipo: 'buff_resistenza', danniTipo: ['contundenti', 'perforanti', 'taglienti'], durataTurni: 1 },
            cd: false,
            tiro_abilita: false
        },
        {
            nome:"Tocco gelido",
            livello:0,
            modificatore:["Carisma"],
            azione:"Azione",
            raggio:"18 metri",
            durata:"Istantanea",
            concentrazione: false,
            desc:"Crei una mano spettrale e scheletrica nello spazio di una creatura entro la portata. Effettua un attacco magico a distanza contro la creatura per assalirla con il gelo della tomba. Se colpisci, il bersaglio subisce 1d8 danni necrotici e non può recuperare punti ferita fino all'inizio del tuo prossimo turno. Fino ad allora, la mano si aggrappa al bersaglio. Se colpisci un bersaglio non morto, questo subisce anche svantaggio ai tiri per colpire contro di te fino alla fine del tuo prossimo turno.",
            effetto:{tipo:'attacco_distanza',danno:'1d8',dannoTipo:'necrotico'},
            cd:false,
            tiro_abilita:true
        },
        {
            nome: "Tocco del Vampiro",
            livello: 3,
            modificatore: ["Carisma", "Intelligenza"],
            azione: "Azione",
            raggio: "Se stesso",
            durata: "1 minuto",
            concentrazione: true,
            desc: "Il tocco della tua mano avvolta dall'ombra può prosciugare la forza vitale degli altri per curare le tue ferite. Effettua un attacco con incantesimo in mischia contro una creatura a tua portata. Se colpisci, il bersaglio subisce 3d6 danni necrotici e tu recuperi punti ferita pari alla metà dei danni necrotici inflitti. Finché l'incantesimo non termina, puoi effettuare nuovamente l'attacco in ciascuno dei tuoi turni come azione.",
            effetto: { tipo: 'attacco_mischia_cura', danno: '3d6', dannoTipo: 'necrotici', cura: 'meta_danno', durataTurni: 10 },
            cd: false,
            tiro_abilita: true
        },
    ],
    cura: [],
     utilita: [
        {
            nome:"Amicizia",
            livello:0,
            modificatore:["Carisma"],
            azione:"Azione",
            raggio:"Se stesso",
            durata:"1 minuto",
            concentrazione: true,
            desc:"Per tutta la durata dell'incantesimo, hai vantaggio su tutte le prove di Carisma dirette contro una creatura a tua scelta che non ti sia ostile. Quando l'incantesimo termina, la creatura si rende conto che hai usato la magia per influenzare il suo umore e diventa ostile nei tuoi confronti. Una creatura incline alla violenza potrebbe attaccarti. Un'altra creatura potrebbe cercare vendetta in altri modi (a discrezione del DM), a seconda della natura della tua interazione con essa.",
            effetto:{tipo:'amicizia', durataTurni:10},
            cd:false,
            tiro_abilita:false
        },
        {
            nome: "Calmare Emozioni",
            livello: 2,
            modificatore: ["Carisma"],
            azione: "Azione",
            raggio: "9 metri",
            durata: "1 minuto",
            concentrazione: true,
            desc: "Tenti di sopprimere le forti emozioni in un gruppo di persone. Ogni umanoide in una sfera con raggio di 6 metri centrata su un punto a tua scelta entro il raggio d'azione deve effettuare un tiro salvezza su Carisma; una creatura può scegliere di fallire questo tiro salvezza se lo desidera. Se una creatura fallisce, scegli uno dei due effetti seguenti. Puoi sopprimere qualsiasi effetto che renda il bersaglio affascinato o spaventato. Quando questo incantesimo termina, qualsiasi effetto soppresso riprende, a condizione che la sua durata non sia scaduta nel frattempo. In alternativa, puoi rendere un bersaglio indifferente alle creature di tua scelta verso cui è ostile. Questa indifferenza termina se il bersaglio viene attaccato o ferito da un incantesimo o se assiste al ferimento di un suo alleato. Quando l'incantesimo termina, la creatura diventa di nuovo ostile, a meno che il DM non decida diversamente.",
            effetto: { tipo: 'calmare_emozioni', raggioMetri: 6, ts: 'Carisma', durataTurni: 10 },
            cd: true,
            tiro_abilita: false
        },
          {
            nome: "Comprensione del Linguaggio",
            livello: 1,
            modificatore: ["Qualsiasi"],
            azione: "Azione Bonus",
            raggio: "Su se stesso",
            durata: "1 ora",
            concentrazione: false,
            desc: "Per 1 ora comprendi ogni linguaggio.",
            effetto: { tipo: 'comprensione_linguaggio', durataOre: 1 },
            cd: false,
            tiro_abilita:false
        },
        {
            nome: "Controllare fiamme",
            livello: 0,
            modificatore: ["Carisma"],
            azione: "Azione",
            raggio: "9 metri",
            durata: "Istantanea o fino a 20",
            concentrazione: false,
            desc: "Scegli una fiamma non magica che puoi vedere entro la gittata e che si adatti a un cubo di 1,5 metri di lato. Puoi influenzarla in uno dei seguenti modi: \n 1)Espandi istantaneamente la fiamma di 1,5 metri in una direzione, a condizione che nella nuova posizione sia presente legna o altro combustibile. \n Spegni istantaneamente le fiamme all'interno del cubo. \n Raddoppia o dimezzi l'area di luce intensa e debole proiettata dalla fiamma, ne cambi il colore o entrambi. L'effetto dura 1 ora. \n Fai apparire delle forme semplici, come la sagoma vaga di una creatura, un oggetto inanimato o un luogo, all'interno delle fiamme e animale a tuo piacimento. Le forme durano 20 minuti. \n Puoi accelerare la cottura di un piatto del 20% \n Se lanci questa magia più volte, puoi avere fino a tre dei suoi effetti non istantanei attivi contemporaneamente e puoi annullare tale effetto come azione.",
            effetto: { tipo: 'controllare_fiamme' },
            cd: false,
            tiro_abilita: false
        },
        {
            nome: "Creare cibo e Acqua",
            livello: 3,
            modificatore: ["Intelligenza"],
            azione: "Azione",
            raggio: "9 metri",
            durata: "Istantanea",
            concentrazione: false,
            desc: "Crei fino a 3 unità di cibo e 3 di acqua. Per ogni unità extra oltre alla base, attingi alle tue scorte personali di cibo/acqua con una perdita di efficienza del 15% (consumi 1 unità di riserva per ottenerne 0.85 convertite).",
            effetto: { tipo: 'crea_cibo_acqua', baseCibo: 3, baseAcqua: 3, efficienzaExtra: 0.85 },
            cd: false,
            tiro_abilita:false
        },
        {
            nome: "Dono della Parlantina",
            livello: 2,
            modificatore: ["Carisma"],
            azione: "Reazione",
            raggio: "Se stesso",
            durata: "Istantanea",
            concentrazione: false,
            desc: "Reazione da usare quando parli a un'altra creatura (richiede di consumare 2 monete d'oro). Rimodelli abilmente i ricordi di chi ascolta nelle tue immediate vicinanze: ogni creatura a tua scelta entro 1,5 metri da te dimentica tutto ciò che hai detto negli ultimi 6 secondi. Quelle creature poi ricorderanno che hai effettivamente detto le parole che pronunci come componente verbale di questo incantesimo.",
            effetto: { tipo: 'alterazione_memoria', raggioMetri: 1.5 },
            cd: false,
            tiro_abilita: false
        },
        {
            nome:"Guida",
            livello:0,
            modificatore:["Carisma"],
            azione:"Azione",
            raggio:"A contatto",
            durata:"1 minuto",
            concentrazione: true,
            desc:"Tocca una creatura consenziente. Una volta prima che l'incantesimo termini, il bersaglio può tirare un d4 e aggiungere il risultato a una prova di caratteristica a sua scelta. Può tirare il dado prima o dopo aver effettuato la prova di caratteristica. Dopodiché l'incantesimo termina.",
            effetto:{tipo:'guida', durataTurni:10},
            cd:false,
            tiro_abilita:false
        },
         {
            nome: "Individua Oggetto",
            livello: 2,
            modificatore: ["Intelligenza"],
            azione: "Azione",
            raggio: "Se stesso",
            durata: "10 minuti",
            concentrazione: true,
            desc: "Descrivi o nomina un oggetto a te familiare. Percepisci la direzione in cui si trova, a patto che sia entro 300 metri da te. Se l'oggetto è in movimento, ne conosci la direzione. L'incantesimo può individuare un oggetto specifico noto se l'hai visto da vicino (entro 9 metri) almeno una volta, oppure l'oggetto più vicino di un tipo particolare (es. un certo tipo di abito, gioiello, arma). L'incantesimo è bloccato da qualsiasi spessore di piombo.",
            effetto: { tipo: 'divinazione_oggetto', raggioMetri: 300, durataTurni: 100 },
            cd: false,
            tiro_abilita: false
        },
        {
            nome: "Individuazione dei Pensieri",
            livello: 2,
            modificatore: ["Intelligenza"],
            azione: "Azione",
            raggio: "Se stesso",
            durata: "1 minuto",
            concentrazione: true,
            desc: "Puoi leggere i pensieri di certe creature. Come azione in ogni turno, puoi concentrarti su una creatura che vedi entro 9 metri (immune se ha Intelligenza 3 o meno o non parla lingue). Apprendi i pensieri superficiali. Come azione puoi sondare più a fondo: il bersaglio deve effettuare un TS su Saggezza. Se fallisce, ottieni informazioni sul suo stato emotivo, ragionamenti e pensieri predominanti. Se ha successo, l'incantesimo termina. Il bersaglio sa che lo stai sondando e può usare un'azione per fare una prova di Intelligenza contrapposta alla tua per terminare l'effetto. Puoi anche cercare pensieri invisibili entro 9 metri (l'incantesimo penetra le barriere tranne 60 cm di roccia, 5 cm di metallo o una sottile lamina di piombo).",
            effetto: { tipo: 'divinazione_pensieri', raggioMetri: 9, ts: 'Saggezza', durataTurni: 10 },
            cd: true,
            tiro_abilita: true
        },
        {
            nome: "Invisibilità",
            livello: 2,
            modificatore: ["Qualsiasi"],
            azione: "Azione",
            raggio: "A contatto",
            durata: "10 minuti",
            concentrazione: true,
            desc: "Una creatura che tocchi diventa invisibile finché l'incantesimo non termina. Qualsiasi cosa il bersaglio indossi o trasporti è invisibile finché si trova sulla persona del bersaglio. L'incantesimo termina se il bersaglio attacca o lancia un incantesimo.",
            effetto: { tipo: 'invisibilita', durataTurni: 100 },
            cd: false,
            tiro_abilita: false
        },
        {
            nome:"Luce",
            livello:0,
            modificatore:["Saggezza"],
            azione:"Azione",
            raggio:"A contatto",
            durata:"20 minuti",
            concentrazione: false,
            desc:"Tocca un oggetto che non superi i 3 metri di dimensione in nessuna direzione. Finché l'incantesimo non termina, l'oggetto emette una luce intensa in un raggio di 6 metri e una luce fioca per altri 6 metri. La luce può essere colorata a piacere. Coprire completamente l'oggetto con qualcosa di opaco blocca la luce. L'incantesimo termina se lo lanci di nuovo o lo annulli con un'azione.",
            effetto:{tipo:'luce', durataTurni:200},
            cd:false,
            tiro_abilita:false
        },
        {
            nome:"Lingue",
            livello:3,
            modificatore:["Carisma"],
            azione:"Azione",
            raggio: "Se stesso",
            durata:"30 minuti",
            concentrazione:false,
            desc:"Questo incantesimo conferisce alla creatura che tocchi la capacità di comprendere qualsiasi lingua parlata che essa ode. Inoltre, quando il bersaglio parla, qualsiasi creatura che conosca almeno una lingua e possa udire il bersaglio ne comprende le parole.",
            effetto:{tipo:'Lingue'},
            cd:false,
            tiro_abilita:false,

        },
        {
            nome:"Luci danzanti",
            livello:0,
            modificatore:["Carisma"],
            azione:"Azione",
            raggio:"18 metri",
            durata:"1 minuto",
            concentrazione: true,
            desc:"Puoi creare fino a quattro luci delle dimensioni di una torcia entro il raggio d'azione, facendole apparire come torce, lanterne o sfere luminose che fluttuano nell'aria per tutta la durata dell'incantesimo. Puoi anche combinare le quattro luci in un'unica forma luminosa vagamente umanoide di taglia Media. Qualunque forma tu scelga, ogni luce emette una luce fioca in un raggio di 3 metri. Come azione bonus nel tuo turno, puoi spostare le luci fino a 18 metri in un nuovo punto entro il raggio d'azione. Una luce deve trovarsi entro 6 metri da un'altra luce creata da questo incantesimo e si spegne se supera il raggio d'azione.",
            effetto:{tipo:'luci_danzanti'},
            cd:false,
            tiro_abilita:false
        },
        {
            nome: "Movimenti del Ragno",
            livello: 2,
            modificatore: ["Qualsiasi"],
            azione: "Azione",
            raggio: "A contatto",
            durata: "20 minuti",
            concentrazione: true,
            desc: "Finché l'incantesimo non termina, una creatura consenziente che tocchi ottiene la capacità di muoversi su, giù e attraverso superfici verticali, nonché a testa in giù lungo i soffitti, avendo le mani libere. Il bersaglio ottiene anche una velocità di scalata pari alla sua velocità di passeggio.",
            effetto: { tipo: 'buff_movimento', durataTurni: 200 },
            cd: false,
            tiro_abilita: false
        },
        {
            nome:"Oggetti irrevomibile",
            livello:2,
            modificatore:["Intelligenza"],
            azione:"Azione",
            raggio:"A contatto",
            durata:"10 minuti",
            concentrazione: false,
            desc:"Toccando un oggetto che pesa non più di 4,5 kg, questo si fissa magicamente sul posto. Tu e le creature che designi quando lanci questo incantesimo potete muovere l'oggetto normalmente. Puoi anche impostare una parola d'ordine che, se pronunciata entro 1,5 metri dall'oggetto, sopprime questo incantesimo per 1 minuto. \n Se l'oggetto è fissato in aria, può sostenere fino a 1800 kg di peso. Un peso maggiore lo fa cadere. Altrimenti, una creatura può usare un'azione per effettuare una prova di Forza contro la tua CD di tiro salvezza. In caso di successo, la creatura può muovere l'oggetto fino a 3 metri.",
            effetto: {tipo:'Oggetto_irrevomibile'},
            cd: false,
            tiro_abilita:false
        }, 
        {
            nome: "Passare Senza Tracce",
            livello: 2,
            modificatore: ["Saggezza"],
            azione: "Azione",
            raggio: "Se stesso",
            durata: "20 minuti",
            concentrazione: true,
            desc: "Un velo di ombre e silenzio si irradia da te, mascherando te e i tuoi compagni dall'individuazione. Per la durata dell'incantesimo, ogni creatura a tua scelta entro 9 metri da te (incluso te) ha un bonus di +10 alle prove di Destrezza (Furtività) e non può essere seguita se non con mezzi magici. Una creatura che riceve questo bonus non lascia impronte o altre tracce del suo passaggio.",
            effetto: { tipo: 'buff_furtivita', raggioMetri: 9, bonus: 10, durataOre: 1 },
            cd: false,
            tiro_abilita: false
        },
        {
            nome: "Passo Velato",
            livello: 2,
            modificatore: ["Saggezza"],
            azione: "Azione bonus",
            raggio: "Se stesso",
            durata: "Istantanea",
            concentrazione: false,
            desc: "Brevemente circondato da una nebbia argentea, ti teletrasporti fino a 4,5 metri in uno spazio libero che puoi vedere.",
            effetto: { tipo: 'teletrasporto', raggioMetri: 4.5 },
            cd: false,
            tiro_abilita: false
        },
        {
            nome:"Prestito di conoscenza",
            livello:2,
            modificatore:["Intelligenza"],
            azione:"Azione",
            raggio:"Se stesso",
            durata:"10 minuti",
            concentrazione:false,
            desc:"Attingi alla conoscenza degli spiriti del passato. Scegli un'abilità in cui non sei competente. Per tutta la durata dell'incantesimo, avrai competenza nell'abilità scelta. L'incantesimo termina prima se lo lanci di nuovo.",
            cd:false,
            tiro_abilita:false
        },
        {
            nome: "Protezione dall'Energia",
            livello: 3,
            modificatore: ["Saggezza"],
            azione: "Azione",
            raggio: "A contatto",
            durata: "1 ora",
            concentrazione: true,
            desc: "Per la durata dell'incantesimo, la creatura consenziente che tocchi ha resistenza a un tipo di danno a tua scelta: acido, freddo, fuoco, fulmine o tuono.",
            effetto: { tipo: 'buff_resistenza', durataOre: 1 },
            cd: false,
            tiro_abilita: false
        },
        {
            nome:"Riparare",
            livello:0,
            modificatore:["Intelligenza"],
            azione:"Azione",
            raggio:"A contatto",
            durata:"1 minuto",
            concentrazione: false,
            desc:"Questo incantesimo ripara una singola rottura o lacerazione in un oggetto che tocchi. Purché la rottura o la lacerazione non superi i 30 centimetri in nessuna dimensione, la ripari senza lasciare traccia del danno precedente. \n Questo incantesimo può riparare fisicamente un oggetto o una costruzione magica, ma non può ripristinare la magia in tale oggetto. \n Questo incantesimo ti permette di compiere microriparazioni ai Robot anche senza conoscenze di Artificeria. \n Lanciare questo incantesimo mentre smonti un oggetto ti fa in modo che ottieni il 5% in più di ingranaggi- \n Mentre lanciare questo incantesimo mentre crei un oggetto riduce la CA di 1.",
            effetto:{tipo:'riparare'},
            cd:false,
            tiro_abilita:false
        },
        {
            nome: "Scassinare",
            livello: 2,
            modificatore: ["Intelligenza", "Carisma"],
            azione: "Azione",
            raggio: "18 metri",
            durata: "Istantanea",
            concentrazione: false,
            desc: "Scegli un oggetto entro il raggio d'azione (una porta, forziere, lucchetto, manette, ecc.) tenuto chiuso da un mezzo mondano o magico. Un bersaglio bloccato da una serratura mondana, incastrato o sbarrato viene sbloccato. Se ha più serrature, se ne sblocca solo una. Se il bersaglio è chiuso con Serratura Arcana, quell'incantesimo è soppresso per 10 minuti. Quando lanci l'incantesimo, un forte colpo udibile fino a 90 metri di distanza emana dall'oggetto.",
            effetto: { tipo: 'sbloccare' },
            cd: false,
            tiro_abilita: false
        },
        {
            nome: "Scurovisione",
            livello: 2,
            modificatore: ["Saggezza"],
            azione: "Azione",
            raggio: "A contatto",
            durata: "8 ore",
            concentrazione: false,
            desc: "Tocchi una creatura consenziente per conferirle la capacità di vedere al buio. Per la durata dell'incantesimo, quella creatura ha scurovisione fino a un raggio di 18 metri.",
            effetto: { tipo: 'buff_visione', raggioMetri: 18, durataOre: 8 },
            cd: false,
            tiro_abilita: false
        },
        {
            nome: "Serratura Arcana",
            livello: 2,
            modificatore: ["Qualsiasi"],
            azione: "Azione",
            raggio: "A contatto",
            durata: "Finché non viene dissolto",
            concentrazione: false,
            desc: "Tocchi una porta, finestra, cancello, forziere o altro ingresso chiuso, che si blocca magicamente. Tu e le creature designate potete aprirlo normalmente. Puoi impostare una parola d'ordine che sopprime l'effetto per 1 minuto se pronunciata entro 1,5 metri. Altrimenti è invalicabile finché non viene rotto o l'incantesimo dissolto. L'incantesimo Scassinare lo sopprime per 10 minuti. Mentre è sotto questo effetto, la CD per rompere l'oggetto o scassinare la serratura aumenta di 10.",
            effetto: { tipo: 'bloccare', cdBonus: 10 },
            cd: false,
            tiro_abilita: false
        },
        {
            nome: "Suggestione",
            livello: 2,
            modificatore: ["Carisma"],
            azione: "Azione",
            raggio: "9 metri",
            durata: "8 ore",
            concentrazione: true,
            desc: "Suggerisci una linea di condotta (una o due frasi) e influenzi magicamente una creatura che vedi entro il raggio d'azione, che può sentirti e capirti (immuni le creature che non possono essere affascinate). La suggestione deve sembrare ragionevole: chiedere atti palesemente autolesionistici fa terminare l'incantesimo. Il bersaglio deve effettuare un TS su Saggezza. Se fallisce, persegue l'azione descritta al meglio. Puoi specificare condizioni scatenanti. L'incantesimo termina se l'azione viene completata in anticipo, o se tu o i tuoi compagni infliggete danni al bersaglio.",
            effetto: { tipo: 'suggestione', ts: 'Saggezza', durataOre: 8 },
            cd: true,
            tiro_abilita: false
        },
        {
            nome: "Vento Custode",
            livello: 2,
            modificatore: ["Saggezza"],
            azione: "Azione",
            raggio: "Se stesso",
            durata: "10 minuti",
            concentrazione: true,
            desc: "Un forte vento (32 km/h) soffia intorno a te in un raggio di 3 metri e si muove con te, rimanendo centrato su di te. Dura per la durata dell'incantesimo e ha i seguenti effetti: assorda te e le altre creature nell'area; spegne fiamme non protette grandi fino a una torcia; l'area è terreno difficile per creature diverse da te; i tiri per colpire con armi a distanza hanno svantaggio se passano attraverso o escono dal vento; respinge vapore, gas e nebbia dispersibili dal vento forte.",
            effetto: { tipo: 'vento_custode', raggioMetri: 3, durataTurni: 100 },
            cd: false,
            tiro_abilita: false
        },
    ]
};