// perks.js

const DATABASE_PERK = {
    "competenze base": [
        { nome: "Acrobata", desc: "Competenza in Atletica e Acrobazia", costo: 4, skills: ["Atletica", "Acrobazia"] },
        { nome: "Addestratore da circo", desc: "Competenza in Addestrare animali e Intrattenere", costo: 3, skills: ["Addestrare animali", "Intrattenere"] },
        { nome: "Allevatore", desc: "Competenza in Addestrare animali e Manodopera", costo: 3, skills: ["Addestrare animali", "Manodopera"] },
        { nome: "Ambasciatore", desc: "Competenza in Storia e Persuasione", costo: 3, skills: ["Storia", "Persuasione"] },
        { nome: "Appassionato della natura", desc: "Competenza in Natura e Addestrare gli animali", costo: 2, skills: ["Natura", "Addestrare gli animali"] },
        { nome: "Artigiano Arcano", desc: "Competenza in Manodopera e Arcano", costo: 3, skills: ["Manodopera", "Arcano"] },
        { nome: "Artista accademico", desc: "Competenza in Storia e Intrattenere", costo: 2, skills: ["Storia", "Intrattenere"] },
        { nome: "Attivista", desc: "Competenza in Natura e Intimidire", costo: 3, skills: ["Natura", "Intimidire"] },
        { nome: "Ballerina", desc: "Competenza in Intrattenere e Acrobazia", costo: 3, skills: ["Intrattenere", "Acrobazia"] },
        { nome: "Baro", desc: "Competenza in Rapidità di mano e Giochi di carte", costo: 3, skills: ["Rapidità di mano", "Giochi di carte"] },
        { nome: "Borseggiatore", desc: "Competenza in Rapidità di mano e Acrobazia", costo: 5, skills: ["Rapidità di mano", "Acrobazia"] },
        { nome: "Bruto", desc: "Competenza in Atletica e Intimidire", costo: 3, skills: ["Atletica", "Intimidire"] },
        { nome: "Cacciatore", desc: "Competenza in Sopravvivenza e Percezione", costo: 4, skills: ["Sopravvivenza", "Percezione"] },
        { nome: "Casalingo", desc: "Competenza in Manodopera e Cucina", costo: 4, skills: ["Manodopera", "Cucina"] },
        { nome: "Cuoco", desc: "Competenza in Natura e Cucina", costo: 4, skills: ["Natura", "Cucina"] },
        { nome: "Detective", desc: "Competenza in Indagare e Intuizione", costo: 3, skills: ["Indagare", "Intuizione"] },
        { nome: "Escursionista", desc: "Competenza in Sopravvivenza e Cucina", costo: 3, skills: ["Sopravvivenza", "Cucina"] },
        { nome: "Esperto di Sopravvivenza", desc: "Competenza in Natura e Sopravvivenza", costo: 4, skills: ["Natura", "Sopravvivenza"] },
        { nome: "Esploratore di Rovine", desc: "Competenza in Storia e Acrobazia", costo: 3, skills: ["Storia", "Acrobazia"] },
        { nome: "Fuggiasco", desc: "Competenza in Rapidità di mano e Furtività", costo: 4, skills: ["Rapidità di mano", "Furtività"] },
        { nome: "Infiltrato", desc: "Competenza in Furtività e Inganno", costo: 5, skills: ["Furtività", "Inganno"] },
        { nome: "Ladro", desc: "Competenza in Furtività e Strumenti da scasso", costo: 7, skills: ["Furtività", "Strumenti da scasso"] },
        { nome: "Lanciatore", desc: "Competenza in Percezione e Rapidità di mano", costo: 4, skills: ["Percezione", "Rapidità di mano"] },
        { nome: "Mago", desc: "Competenza in Arcano e Intuizione", costo: 3, skills: ["Arcano", "Intuizione"] },
        { nome: "Missionario", desc: "Competenza in Atletica e Religione", costo: 4, skills: ["Atletica", "Religione"] },
        { nome: "Pastore", desc: "Competenza in Persuasione e Religione", costo: 3, skills: ["Persuasione", "Religione"] },
        { nome: "Poker Face", desc: "Competenza in Inganno e Giochi di carte", costo: 3, skills: ["Inganno", "Giochi di carte"] },
        { nome: "Predicatore", desc: "Competenza in Religione e Intimidire", costo: 3, skills: ["Religione", "Intimidire"] },
        { nome: "Prestigiatore", desc: "Competenza in Rapidità di mano e Persuasione", costo: 4, skills: ["Rapidità di mano", "Persuasione"] },
        { nome: "Oracolo", desc: "Competenza in Percezione e Arcano", costo: 4, skills: ["Percezione", "Arcano"] },
        { nome: "Oratore", desc: "Competenza in Intuizione e Intrattenere", costo: 4, skills: ["Intuizione", "Intrattenere"] },
        { nome: "Ricattatore", desc: "Competenza in Investigare e Intimidire", costo: 4, skills: ["Investigare", "Intimidire"] },
        { nome: "Ricercatore magico", desc: "Competenza in Arcano e Investigare", costo: 4, skills: ["Arcano", "Investigare"] },
        { nome: "Scassinatore", desc: "Competenza in Percezione e Strumenti da scasso", costo: 5, skills: ["Percezione", "Strumenti da scasso"] },
        { nome: "Selvaggio", desc: "Competenza in Addestrare Animali e Atletica", costo: 4, skills: ["Addestrare Animali", "Atletica"] },
        { nome: "Spia", desc: "Competenza in Furtività e Indagare", costo: 5, skills: ["Furtività", "Indagare"] },
        { nome: "Storico", desc: "Competenza in Storia e Arcano", costo: 3, skills: ["Storia", "Arcano"] },
        { nome: "Studente", desc: "Competenza in Giochi di carte e Storia", costo: 3, skills: ["Giochi di carte", "Storia"] },
        { nome: "Taverniere", desc: "Competenza in Cucina e Giochi di Carte", costo: 3, skills: ["Cucina", "Giochi di Carte"] },
        { nome: "Truffatore", desc: "Competenza in Inganno e Intuizione", costo: 3, skills: ["Inganno", "Intuizione"] },
        { nome: "Tuttofare", desc: "Competenza in Manodopera e Strumenti da Scasso", costo: 4, skills: ["Manodopera", "Strumenti da Scasso"] },
        { nome: "Urbex professionale", desc: "Competenza in Sopravvivenza e Strumenti da scasso", costo: 6, skills: ["Sopravvivenza", "Strumenti da scasso"] },
        { nome: "Voce del popolo", desc: "Competenza in Inganno e Persuasione", costo: 2, skills: ["Inganno", "Persuasione"] }
    ],
    "background": [
        { nome: "Armato", desc: "Inizia l'avventura con un'arma a tua scelta in cui hai competenza. Munizioni: 10 per arco/balestra, 3 per pistola.", costo: 3, skills: [] },
        {nome:"Artigiano Alimentare",desc:"Ottieni competenza in Cucina. inoltre quando prepari piatti deliziosi danno un potenziamento per 2 ore dove il tempo delle azioni in corso sono accelerate del 20% (anche la guarigione e riposo)",costo:6,skills:['Cucina']},
        { nome: "Autoctono", desc: "Possiedi una casa in città; loot casuale deciso dal master.", costo: 8, skills: [] },
        { nome: "Avventuriero", desc: "Inizia con zaino capiente, cibo e acqua per 1 giorno, e sacco a pelo.", costo: 3, skills: [] },
        { nome: "Fortunato", desc: "2 gettoni fortuna al giorno utilizzabili per migliorare loot o tirare con vantaggio.", costo: 10, skills: [] },
        { nome: "Fuori dal mondo", desc: "Perk che ti isola dal linguaggio comune: perdi la lingua Verbum dalle lingue conosciute.", costo: 1, skills: [] },
        { nome: "Lingue", desc: "Conosci una lingua in più; selezionabile. Riacquistabile più volte.", costo: 2, skills: [], repeats: true },
        {nome:"Soldato",desc:"Ottieni competenza nei Ts su Forza e Costituzione e competenza di livello 1 su due armi a tua scelta",costo:-10,skills:[]}, 
        { nome: "Urbex", desc: "Competenza in Acrobazia e vantaggi nell'analisi degli edifici.", costo: 3, skills: ["Acrobazia"] },
        { nome: "Sfortunato", desc: "Due volte a sessione il master può obbligarti a fare un tiro con svantaggio.", costo: -6, skills: [] },
        { nome: "Hai qualcosa nell'occhio", desc: "Perk unico: solo un personaggio può averlo per campagna.", costo: 20, skills: [] },
        { nome: "Nascita straordinaria", desc: "Perk unico: solo un personaggio può averlo per campagna.", costo: 20, skills: [] }
        ],
    "carisma e sociale": [
        { nome: "Amicizia", desc: "(Richiede un altro personaggio che abbia questo perk abbinato al tuo) Come reazione se il tuo amico è nel raggio di tre metri, puoi aumentare la sua CA di 2.", costo: 2, skills: [] },
        { nome: "Artista", desc: "Ogni giorno riduci la follia del party di 1d4, ottieni competenza in Intrattenere, Inoltre puoi scegliere una di queste specializzazioni: - Musicista: Ottieni il perk Orecchio fino - Scrittore: competenza in manodopera - Danzatore: +2 ai tiri su acrobazia - Scrittore/narratore: studio accelerato del 25% - Pittore: i tuoi disegni sono così realistici da essere considerati foto.", costo: 5, skills: ["Intrattenere"] },
        { nome: "Balbuzziente", desc: "Balbuzie o accento insolito: ottieni svantaggio nelle prove Intimidire e Inganno.", costo: -2, skills: [] },
        { nome: "Cicatrici", desc: "Ottieni competenza in Intimidire ma -3 alle altre prove di Carisma.", costo: -3, skills: ["Intimidire"] },
        { nome: "Codice Etico", desc: "Possiedi un codice morale/legale rigido. Quando compi un'azione ritenuta immorale subisci -2 ai tiri di Carisma per 24 ore.", costo: -3, skills: [] },
        { nome: "CroceRossina", desc: "Se non aiuti un compagno ferito ottieni sensi di colpa che aumentano la Follia e danno il perk Insonne. Gli effetti si possono sovrapporre fino a 4 volte.", costo: -7, skills: [] },
        { nome: "Imbarazzo", desc: "Quando fallisci una prova di Carisma su una persona, avrai svantaggio su prove di Carisma su di lei e -1 ai tiri abilità se la persona è nel raggio di vista.", costo: -4, skills: [] },
        { nome: "Introversione", desc: "Ottieni svantaggio nelle prove di Carisma.", costo: -4, skills: [],disadvantage: ["Intimidire", "Persuasione", "Intrattenere", "Inganno"] },
        { nome: "Misogino/Androgeno", desc: "Ottieni svantaggio nelle prove di Carisma sul sesso opposto.", costo: -3, skills: [] },
        { nome: "Panico Sociale", desc: "Se sei in presenza di più di quattro persone ottieni svantaggio nelle prove di Carisma.", costo: -2, skills: [] },
        { nome: "Paranoico", desc: "Hai una paranoia che richiede comportamenti di evitamento quotidiani; se ignorati vai in panico fino a compiere l'azione.", costo: -4, skills: [] },
        { nome: "Rancoroso", desc: "Quando qualcuno ti fa un torto subisci vari malus: +2 CD alle prove di Medicina se lo curi, -40% velocità studio/creazione lavorando con lui, +4 CD su azioni coordinate.", costo: -5, skills: [] },
        { nome: "Scontroso", desc: "Hai svantaggio su Intuizione, Intrattenere, Persuasione verso persone che non ti piacciono (ogni 5 persone te ne può piacere una).", costo: -2, skills: [] },
        { nome: "Bel viso", desc: "Ottieni +1 a Carisma e +2 a Intrattenere.", costo: 2, skills: [] },
        { nome: "Guida", desc: "Se un alleato sta facendo nel raggio di 3 metri una prova abilità/usando oggetti in cui tu hai competenza, puoi dargli un bonus di 1d6 (deve poterti vedere/ascoltare).", costo: 3, skills: [] },
        { nome: "Uniti siamo più forti", desc: "Se nel raggio di 3 metri ci sono almeno 2 alleati, tutti ottenete PF fortuna temporanei pari al modificatore di Carisma. Attivabile una volta a battaglia.", costo: 3, skills: [] },
        { nome: "Leader nato", desc: "Ottieni +1 al modificatore Carisma per due membri del party che ti accompagnano (fino a +3).", costo: 3, skills: [] },
        { nome: "Mente ferrea", desc: "Quando vai nel panico puoi usare subito una reazione per usare Pulizia Mentale e rimuoverlo ottenendo +2. Attiva una volta per sessione.", costo: 4, skills: [] },
        { nome: "Seduttore", desc: "Ottieni vantaggio nelle prove Carisma contro un sesso a tua scelta.", costo: 4, skills: [] },
        { nome: "Solitario", desc: "Se sei da solo ottieni +2 a tutte le prove abilità/competenze e migliori risultati nelle esplorazioni.", costo: 3, skills: [] },
        { nome: "Vendicativo", desc: "Quando un tuo alleato subisce un danno reale, ottieni vantaggio negli attacchi verso chi l'ha ferito finché non lo colpisci due volte.", costo: 4, skills: [] },
        { nome: "Vicinanza", desc: "Quando un alleato sta venendo curato o deve fare un TS, puoi usare una reazione per ridurre la CD della prova in base al tuo modificatore di Carisma. Usi a riposo lungo pari al modificatore di Carisma.", costo: 5, skills: [] },
        { nome: "Voce calma", desc: "Ottieni competenza in Persuasione. Quando un alleato è spaventato/affascinato/panico puoi usare reazione/azione bonus per un tiro di Persuasione per rimuovere l'effetto se superi la CD.", costo: 3, skills: ["Persuasione"] }
    ],
    "combattimento": [
        { nome: "Arti marziali", desc: "Usi Destrezza per colpire e danni con mani nude. Se il bersaglio fallisce un attacco corpo a corpo, puoi costringerlo a un TS su Forza (CD 8 + Destrezza + competenza) per disarmarlo o atterrarlo.", costo: 6, skills: [] },
        { nome: "Assassino sprecato", desc: "Quando sorprendi un nemico in combattimento ottieni +1d6 danno extra.", costo: 4, skills: [] },
        { nome: "Assetato di adrenalina", desc: "Colpire un nemico ti dà +1 al prossimo tiro per colpire, fino a +3. L’effetto si resetta se manchi o non colpisci per un turno.", costo: 3, skills: [] },
        { nome: "Colpisci e fuggi", desc: "Puoi attaccare un nemico mentre ti muovi e attraversare il suo spazio; il danno subisce -2.", costo: 4, skills: [] },
        { nome: "Colpo pesante", desc: "Dopo un colpo riuscito puoi usare un’azione bonus per rallentare il bersaglio di 3 metri.", costo: 3, skills: [] },
        { nome: "Colpo alla testa", desc: "Critico a distanza +2d6 danno. Scegli un numero fortunato all’inizio della campagna; quel tiro diventa critico.", costo: 7, skills: [] },
        { nome: "Concentrazione ferrea", desc: "Hai vantaggio nelle prove per non perdere la concentrazione.", costo: 2, skills: [] },
        { nome: "Contro un esercito", desc: "Se sei circondato da almeno 2 nemici in mischia, ottieni +1d6 danno.", costo: 2, skills: [] },
        { nome: "Cura delle armi", desc: "Ottieni +2 ai tiri per colpire con la stessa arma dopo 3 combattimenti, se hai almeno competenza 3 con quell’arma.", costo: 5, skills: [] },
        { nome: "Duellante", desc: "Se attacchi un solo avversario, ottieni 5 PF fortuna temporanei usabili solo contro quel nemico.", costo: 2, skills: [] },
        { nome: "Esecutore", desc: "Quando un nemico è sotto la sua vita, puoi usare un’azione bonus per +2d4 danno da mischia, volte al giorno pari al modificatore di Forza.", costo: 3, skills: [] },
        { nome: "Fino all'ultimo", desc: "Ignori gli effetti delle ferite reali fino a fine scontro. Le ferite attuali hanno il 40% di probabilità di peggiorare di grado.", costo: 6, skills: [] },
        { nome: "Fuggi", desc: "Appena entri in combattimento puoi usare un’azione bonus per Scatto o Disimpegno (2/giorno).", costo: 3, skills: [] },
        { nome: "Lotta", desc: "Entri in furia per 1 min, ottieni bonus competenza ai colpi ma perdi concentrazione se non attacchi per un turno (2/giorno).", costo: 4, skills: [] },
        { nome: "Impassibile", desc: "Rimanendo fermo per un turno ottieni +2 CA.", costo: 2, skills: [] },
        { nome: "Guerriero", desc: "+5 PF fortuna massimi. Due volte al giorno puoi rigenerare 1d4 + mod Costituzione con un’azione in combattimento.", costo: 6, skills: [] },
        { nome: "Mani nude 1", desc: "Aumenti il danno da colpi senza armi a 1d4 + mod Forza.", costo: 2, skills: [] },
        { nome: "Mani nude 2", desc: "Aumenti il danno da colpi senza armi a 1d6 + mod Forza.", costo: 4, skills: [], requires: "Mani nude 1" },
        { nome: "Mani nude 3", desc: "Aumenti il danno da colpi senza armi a 1d8 + mod Forza.", costo: 6, skills: [], requires: "Mani nude 2" },
        { nome: "Memento Mori", desc: "Sotto 1/3 PF fortuna puoi abbassare la CA di 2 per vantaggio agli attacchi per 1 min (richiede concentrazione, 1/giorno).", costo: 4, skills: [] },
        { nome: "Muro di Carne", desc: "Quando proteggi un alleato e l’attacco colpisce, puoi subire tu il danno ridotto del tuo mod Costituzione.", costo: 5, skills: [] },
        { nome: "Nato per combattere", desc: "Rigeneri 1d6 + mod Destrezza PF fortuna all’inizio del combattimento.", costo: 6, skills: [] },
        { nome: "Reattività", desc: "Quando perdi un punto ferita reale guadagni subito 1d6+mod di costituzione al posto del lancio normale", costo: 5, skills: [] },
        { nome: "Ottima mira", desc: "+1 ai colpi e danni con armi a distanza se hai competenza di livello 2 con quell’arma.", costo: 5, skills: [] },
        { nome: "Scatto Reattivo", desc: "Con Bloccare, se il nemico fallisce il TS, ottieni un attacco in mischia gratuito con danno dimezzato.", costo: 4, skills: [] },
        { nome: "Scivolata", desc: "Mentre ti muovi e subisci un attacco di opportunità, puoi usare la reazione per schivarlo automaticamente.", costo: 4, skills: [] },
        { nome: "Sempre pronto", desc: "Entri automaticamente primo in combattimento (2/giorno).", costo: 3, skills: [] },
        { nome: "Sorte improvvisa", desc: "Scegli 4 numeri. Se tiri uno di questi, il colpo è critico. I 2 successivi attacchi contro di te hanno vantaggio. Uso al giorno pari al mod Saggezza.", costo: 4, skills: [] },
        { nome: "Esitazione", desc: "All’inizio del combattimento non puoi usare reazioni e perdi 3 metri di velocità nel primo turno.", costo: -5, skills: [] },
        { nome: "Pacifista", desc: "I tuoi attacchi infliggono 1d4 danno in meno.", costo: -4, skills: [] },
        { nome: "Paralisi", desc: "Quando finisci PF o subisci 1 PF, fai TS Saggezza 14 o resti stordito un turno. Max 3 volte a sessione.", costo: -8, skills: [] },
        { nome: "Fifone", desc: "Se entri nel raggio d’attacco di un nemico, sei spaventato una sola volta per combattimento.", costo: -4, skills: [] },
        { nome: "Gambe pesanti", desc: "Immediatamente davanti al pericolo perdi metà della velocità per un turno.", costo: -4, skills: [] },
        { nome: "Mani di burro", desc: "Quando vieni attaccato, fai TS Costituzione 10 o l’arma cade e serve un’azione per riprenderla.", costo: -4, skills: [] },
        { nome: "Scoordinato", desc: "Muovendoti e incontrando un ostacolo hai il 50% di cadere.", costo: -4, skills: [] },
        { nome: "Troppo entusiasta", desc: "-2 CA, se fallisci un attacco il nemico ottiene +2 al prossimo tiro contro di te, ma tu ottieni +2 ai tuoi tiri per colpire. Hai 1d4 danni in più sul primo attacco che compi.", costo: -7, skills: [] }
    ],
    "fisico e salute": [
        { nome: "Atleta", desc: "Competenza Atletica, +1 Stamina", costo: 6, skills: ['Atletica'] },
        { nome: "Facchino esperto", desc: " Puoi trasportare il doppio degli oggetti senza consumare Stamina extra per il peso. Inoltre, estrarre un oggetto dallo zaino per darlo a un alleato conta come Azione Bonus invece che Azione.", costo: 3, skills: ['Atletica'] },
        {nome:"Fisico Perfetto",desc:"Ottieni +3 ai tiri contro essere avvelenato o ammalarti",costo:-3,skills:[]},
        { nome: "Palestrato", desc: "+1 Forza, +1 Costituzione, competenza TS Forza", costo: 7, skills: [] },
        { nome: "Grande taglia", desc: "Sei alto almeno 1.80 metri. e hai una muscolatura possente. Ottieni +2 a Forza e +1 a Costituzione. Ma ottieni svantaggio nelle prove di Furtivita' e la tua velocita' e' ridotta di 2 metri. ", costo: 8, skills: [] },
        { nome: "Parkurista", desc: "Ottieni competenza in Acrobazia e i danni da caduta sono ridotti della metà.", costo: 4, skills: ['Acrobazia'] },
        { nome: "Piccola taglia", desc: " Sei piu' basso di 1.50 metri. Ottieni +2 a Destrezza e competenza in furtivita, la tua velocita' aumenta di 2 metri. La tua Costituzione e' ridotta di -2 ", costo: 9, skills: ['Furtività'] },
        { nome: "Resistenza", desc: "Meno probabilita' di ammalarsi, infezione rallentata", costo: 3, skills: [] },
        { nome: "Anoressico", desc: "Ottieni -2 in forza, -1 in costituzione, sei piu' vittima della morte di stenti (Il tuo fabbisogno di cibo è aumentato del 20%). Svantaggio nei tiri Forza Se otterrai il buff Ben Nutrito per un totale di 24 ore, questi debuff si toglieranno e questo perk si trasformerà in Sottopeso", costo: -8, skills: [] },
        { nome: "Anemico", desc: " Dopo 4 ore, recuperi solo metà della Stamina (arrotondata per difetto). Inoltre, la condizione Sanguinante su di te non può essere rimossa se non con l'intervento di qualcuno che abbia almeno Medicina 2 (non puoi medicarti da solo per fermare l'emorragia efficacemente).", costo: -7, skills: [] },
        { nome: "Anziana", desc: "Ottieni -1 alla stamina, -1 alla costituzione, -1 alla forza, velocità ridotta di 2 metri.Ottieni miope e duro d'orecchi. Ottieni +2 in Saggezza o Carisma, oppure +1 in entrambi.", costo: -10, skills: [] },
        { nome: "Artrite", desc: "Se compi l'azione Scatto o due attacchi più di una volta, devi fare un ts su Costituzione (CD12), se lo fallisci perdi 1d6 punti fortuna e la tua velocità è ridotta di un terzo fino al prossimo riposo lungo.", costo: -7, skills: [] },
        { nome: "Asmatico", desc: "Sotto Sforzo: Quando la tua Stamina scende a 2 o meno, ottieni Svantaggio a tutte le prove di Atletica, Acrobazia e ai Tiri Salvezza su Costituzione.Crisi Respiratoria: Se esaurisci completamente la Stamina (0 tacche), entri immediatamente in uno stato di affanno grave: sei Incapacitato (non puoi compiere azioni) finché non recuperi almeno 1 tacca di Stamina tramite riposo.Recupero Lento: Durante un riposo breve, non puoi recuperare più di 2 tacche di Stamina, a meno che tu non utilizzi 10 risorse comuni mediche.", costo: -5, skills: [] },
        { nome: "Cagionevole", desc: "Ottieni -3 ai tiri contro essere avvelenato o ammalarti", costo: -5, skills: [] },
        { nome: "Cieco", desc: "Non vedi! Fallisci automaticamente le prove riguardo lo sguardo.Ottieni maestria in Percezione. E riⁿesci a percepire le creature che si muovono e fanno rumore nel raggio di 18 metri. Ottieni -6 alla percezione passiva e il perk Scoordinato", costo: -15, skills: [] },
        { nome: "Diabete tipo I", desc: "Ipoglicemia: Se non mangi per un giorno o esaurisci la Stamina (0 tacche), ottieni Svantaggio a tutti i tiri e sei Accecato oltre i 3 metri.Iperglicemia: Se mangi senza aver consumato almeno 2 tacche di Stamina nelle ultime 4 ore, ottieni –2 a Saggezza/Carisma e i tiri mentali/incantesimi richiedono Concetrazione CD 12.", costo: -4, skills: [] },
        { nome: "Diabete tipo II", desc: "(Include Diabete di Tipo I). Dipendenza da Insulina: Ogni 3 giorni senza insulina (5 risorse mediche) perdi 1 PF Reale al giorno (non curabile finché non ti stabilizzi).", costo: -6, skills: [] },
        { nome: "Duro d'orecchi", desc: "Hai svantaggio nelle prove inerenti l'udito e ottieni -2 alla percezione passiva.", costo: -2, skills: [] },
        { nome: "Fragile", desc: "Hai svantaggio nei CD per subire l’effetto di Sanguinamento e i CD delle tue ferite aumentano di +3", costo: -6, skills: [] },        
        { nome: "Guaritore lento", desc: "Ci metti una giornata e mezzo per rigenerare 1 punto ferita reale", costo: -4, skills: [] },
        { nome: "Miope", desc: "–2 Percezione Passiva e svantaggio nelle prove di percezione ", costo: -2, skills: [] },
        { nome: "Naso sensibile", desc: "Ottieni svantaggio nelle prove di Medicina. Di fianco a fonti di cattivo odore (cadaveri in decoposizione, cibo scaduto...) ottieni -2 a Saggezza.", costo: -2, skills: [] },
        { nome: "Obeso", desc: "Malus Fisici: –4 Atletica, –2 Stamina Max, Velocità –3 m. Malus Inclusi: Asmatico (+7) e Diabete I (+4). Buff Costituzione: +2 Buff Denutrizione: Quando la tua fame deve salire a uno stadio superiore al 2, ottieni automaticamente 0.15 punti fame. Puoi approfittare di questo “cuscinetto” un totale di 40 volte, ma ogni volta che consumi una tacca di stamina consumi 1d4+Stadio di Fame utilizzi. Dopo che hai consumato gli utilizzi questo perk viene rimosso totalmente con tutti i suoi buff e debuff e si trasformerà in Sovrapeso.", costo: -14, skills: [] },
        { nome: "Schizofrenico", desc: "Inizi che la tua follia è a metà. Puoi sperimentare illusioni che solo tu vedi.", costo: -5, skills: [] },
        { nome: "Senza occhio", desc: "Percezione passiva -6. Svantaggio prove a Percezione.", costo: -6, skills: [] },
        { nome: "Sottopeso", desc: "Ottieni -1 in forza, il tuo fabbisogno alimentare è aumentato del 10%. Se ottieni il buff ben nutrito per un totale di 12 ore, questi debuff scompariranno insieme a questo perk.", costo: -4, skills: [] },
        { nome: "Sopvrappeso", desc: "–2 Atletica, Velocità –1 m, –1 Stamina Buff Denutrizione: Quando la tua fame deve salire a uno stadio superiore al 2, ottieni automaticamente 0.15 punti fame.  Puoi approfittare di questo “cuscinetto” un totale di 20 volte, ma ogni volta che consumi una tacca di stamina consumi 1d4+Stadio di Fame utilizzi.Dopo che hai consumato gli utilizzi questo perk viene rimosso totalmente con tutti i suoi buff e debuff.", costo: -4, skills: [] },
        { nome: "Tumore magico", desc: "Il tuo personaggio non supererà i 7 giorni. Dal giorno 5 ottieni -1d6 a ogni tiro per colpire; giorno 6 due stadi di fatica; giorno 7 morirai.", costo: -8, skills: [] },
        { nome: "Zoppo", desc: "La tua velocità e' dimezzata. Ottieni svantaggio nelle prove di Atletica e Acrobazia ", costo: -10, skills: [] },
    ],
    "Personalità e Fobie": [
        { nome: "Abbandono", desc: "Vai nel panico se rimani da solo per più di un'ora.", costo: -3, skills: [] },
        { nome: "Agofobico", desc: "Le prove di medicina per medicarti aumentano di +2 al CD, vai nel panico se vieni a contatto con gli aghi.", costo: -4, skills: [] },
        { nome: "Agorafobico", desc: "Entri in Panico quando sei in spazi molto aperti.", costo: -3, skills: [] },
        { nome: "Alcolista", desc: "Senza alcool per troppo tempo ottieni un debuff -2 ad ogni tiro abilità.", costo: -3, skills: [] },
        { nome: "Claustrofobico", desc: "Entri in Panico quando sei in spazi chiusi.", costo: -2, skills: [] },
        { nome: "Cleptomane", desc: "Quando entri in una nuova zona devi prendere qualcosa. Se non lo fai aumenta la Follia e avrai -2 a Percezione, Intuizione, Indagare finché non riesci a tornare per prendere qualcosa.", costo: -4, skills: [] },
        { nome: "Emofobico", desc: "Entri in Panico se entri in contatto col sangue oppure c’è troppo sangue intorno.", costo: -4, skills: [] },
        { nome: "Insettofobia", desc: "Vai nel panico alla presenza di grandi quantità di insetti o insetti giganti; ottieni -2 a Carisma vicino a persone con tratti da insetto.", costo: -2, skills: [] },
        {nome: "Irascibile", desc:"Se fallisci una qualsiasi azione, la tua prossima avrà un +1 ai CD per completarla (Si sovrappone fino ad arrivare a 4, a quel punto il personaggio si arrabbierà e si fermerà per un ora interrompendo l'azione in corso e resetterà il malus) (i Fallimenti critici (1 o fallimenti di alta differenza come in Medicina e Alchimia) alzano di +2.)",costo:-4,skills:[]},
        {nome:"Ipocondriaco",desc:"Se hai uno stadio di malattia aumenta la tua follia e il tempo delle tue azioni aumenta del 20%.",costo:-3,skills:[]},
        { nome: "Occhi della paura", desc: "Vantaggio su prove abilità e attacchi se sei in stato di Panico.", costo: 6, skills: [] },
        { nome: "Ossesione del pulito", desc: "Ogni giorno consumerai 2 ore, 3 materiali medici di base e 4 alchemici automaticamente per pulire tutta la base. La base sarà così igenizzata che ogni medicazione in essa avrà il CD ridotto di 1. Se qualcuno ti blocca, non hai i materiali o non riesci a pulire per cause maggiore, la tua follia aumenterà.", costo: -4, skills: [] },
        { nome: "Paura del buio", desc: "Vai nel panico al buio e di notte se sei fuori casa.", costo: -5, skills: [] },
        { nome: "Perfezionista", desc: "Quando inizi una azione e devi fare un tiro abilità se il risultato è superiore o pari a 20 il tempo rimasto dell'azione è ridotto del 10% sennoʻ aumenta del 20%", costo: -4, skills: [] },
        { nome: "Pessimista", desc: "Quando fallisci una prova o attacco ottieni un -1 alla prova successiva, effetto sovrapponibile fino a -5.", costo: -4, skills: [] },
        {nome:  "Rilassato",desc:"Impieghi +10% nel compiere ogni azi9ne (tranne guarire) peroʻ quando ricdvi la follia è ridotta del 15%",costo:-4,skills:[]},
        { nome: "Sadismo", desc: "Ottieni bonus temporanei quando infliggi sofferenza a persone non infette (max 4/giorno).", costo: 3, skills: [] },
        { nome: "Sadismo patologico", desc: "Include Sadismo; se non ottieni bonus da Sadismo per troppo tempo ottieni svantaggio in Intelligenza/Carisma/Saggezza e la Follia aumenta.", costo: -6, skills: [] },
        { nome: "Sensibile", desc: "Se qualcuno vicino a te ha Panico, hai il 30% di ottenerlo anche tu. Effetto sovrapponibile.", costo: -2, skills: [] },
        { nome: "Traumafobia", desc: "Entri in Panico se perdi un punto vita reale.", costo: -3, skills: [] },
        {nome:"Uccello del Malagurio",desc:"Se sei in base gli alleati impiegano +10% di tempo in più a curarsi.",costo:-6,skills:[]},
        { nome: "Vertigini", desc: "Entri in Panico se sei ad alte altezze.", costo: -3, skills: [] },
    ],
    "magici": [
    { nome: "Apprendista mago", desc: "Ottieni +4 nella mana", costo: 3, skills: [] },
    { nome: "Flusso magico", desc: "Se hai usato la tua azione per castare un incantesimo di livello 1 o superiore e non ti sei ancora mosso, puoi usare una azione bonus per lanciare un trucchetto", costo: 4, skills: [] },
    { nome: "Incantesimo preferito", desc: "Conosci così bene un incantesimo che puoi castarlo spendendo 1 di mana in meno. L'incantesimo deve essere di livello 1 o inferiore ( se è un trucchetto spendi un punto mana una volta sì e una no). Puoʻ essere incisa sul tuo corpo come tatuaggio. L’incantesimo o trucchetto deve essere comprato separatamente.", costo: 5, skills: [] },
    { nome: "Trasmettitore magico", desc: "Puoi passare punti mana a un altro incantatore che tocchi come azione bonus. Il limite dei punti che puoi trasferirli alla volta e’ pari a ¼ dei tuoi punti mana. Puoi passare punti mana sotto allo zero a costo della tua vita. I punti che trasferisci non possono superare i punti massimi che l’incantatore può avere.", costo: 3, skills: [] },
    ],
    "razziali": [
    { nome: "Carapace/Esoscheletro duro", desc: "Ottieni +2 alla CA ma -1 metro di velocita", costo: 3, skills: [] },
    { nome: "Sensibilità alle temperature", desc: "Ottieni debolezza ai danni da gelo o da fuoco (tua scelta)", costo: -4, skills: [] },
    { nome: "Fiuto eccezionale", desc: "Hai +2 in percezione passiva. Ottieni competenza in Percezione. Puoi provare a fare un tiro su Percezione per individuare persone/infetti nell'area circostante.", costo: 7, skills: ["Percezione"] },
    { nome: "Lingua prensile", desc: "Puoi usare un'azione per allungare la lingua di 3 metri. La tua lingua puo' afferrare gli oggetti e trainare i bersagli se falliscono un tiro su Forza contrapposto.Dopo aver attirato un bersaglio l’abilita’ si deve ricaricare per un turno", costo: 5, skills: [] },
    { nome: "Produrre veleni", desc: "Puoi produrre 5ml di veleno (abbastanza per avvelenare qualcuno o scompargerlo su un attacco di un'arma) rinunciando a 0.2 della tua barra dell’acqua.\nIl CD del veleno è (8+modificatore di Alchemia(int))\nPuoi scegliere un veleno alla creazione dell'avventura. Il veleno rimarrà tale per tutta l'avventura.\nCome alternativa al posto di produrre il veleno puoi avere un pungiglione con cui puoi fare un attacco da mischia (usi il tuo modificatore Forza o Destrezza a tua scelta per attaccare, non sommi la competenza).\nIn questo modo oltre al CD contro il veleno infliggi anche 1d4 di danni. Ma in questo modo non puoi produrlo da fuori dal tuo corpo.\nTipi di veleni selezionabili:\nEmotossine (Causa molti danni (circa 2d6 danni se riesce il tiro metà)\nNeurotossine (Paralizzato per un turno)\nNeurotossine Ottiche (Accecano il bersaglio per un turno)\nAllucinogeni (Causa Paura per un turno)\nMiotossine (Causa danni quando il bersaglio si muove (1d4) o compie azioni per 2 turni)\nBlocco Respirazione (Incapacitato per un turno)\nGestrotossine (Immobilizzato per un turno)\nOttieni resistenza ai veleni.E chiunque superi il TS o finisca l’effetto dei tuoi veleni ottiene una resistenza di 2 minuti.", costo: 8, skills: [] },
    { nome: "Termoregolazione", desc: "Ottieni resistenza ai danni da gelo o da fuoco", costo: 4, skills: [] },
    { nome: "Scivolata(Pinguinosa)", desc: "Puoi usare un'azione bonus per fare in modo di rendere il tuo movimento senza attivare attacchi di opportunità. Questa azione puoi compierla 2 volte ogni 4 ore di riposo.", costo: 6, skills: [] },
    { nome: "Trance", desc: "Impieghi solo 4 ore per rigenerare una barra di sonno e 2 ore per rigenerare quella di stamina.", costo: 12, skills: [] },
    { nome: "Volo", desc: "Ottieni una velocità di volo pari a metà della tua velocità.Puoi volare per la mappa volando riducendo i pericoli consumando il doppio della stamina.", costo: 8, skills: [] },
    { nome: "Zampe agili", desc: "Ottieni +3 di Arrampicata, ottieni competenza in Furtivita’ e Acrobaziacata, ottieni competenza in Furtivita’ e Acrobazia", costo: 7, skills: ["Furtività","Acrobazia"] },
    ],
    "sopravvivenza": [
    { nome: "Angelo della casa", desc: "I tuoi piatti deliziosi danno lo stato Ben Nutrito anche se la barra del bersaglio non è piena. Se il bersaglio era già Ben Nutrito i tempi di cura accellerano di un ulteriore 10%.", costo: 4, skills: [] },
    {nome:"Alchimista disperato",desc:"Puoi spendere 3 ore per trasformare 10 unità di cibo avariato in 1d4+mod saggezza unità alchemiche.",costo:4,skills:[]},
    { nome: "Arrampicatore", desc: "Ottieni +3 metri alla velocità di arrampicata. Ottieni vantaggio nelle prove di Atletica per arrampicarti.Ottieni competenza in Atletica.", costo: 3, skills: ["Atletica"] },
    { nome: "Addamento alimentare", desc: "L’effetto Appena Nutrito dura 2 ore in più e durante l’effetto la tua barra alimentare non scende", costo: 5, skills: [] },
    { nome: "Cacciatore della notte", desc: "La tua visuale di notte e' aumentata di 6 metri e ottieni competenza in furtivita' durante la notte.", costo: 3, skills: [] },
    { nome: "Carroarmato", desc: "Puoi sopportare un livello in più di Fatica. Ottieni il livello 0.5 che ti dà -1d4 ad ogni tiro abilità e per colpire. Questo livello sarà il primo che otterrai. Il secondo sarà lo stadio 1", costo: 6, skills: [] },
    { nome: "Casalinga esperta", desc: "La cucina richiede 1 risorsa in meno alimentare, 0.5 in meno dell'acqua e 1 ora in meno.", costo: 5, skills: [] },
    { nome: "Conserva", desc: "Puoi spendere 4 ore e 4 materiali alchemici per far in modo che la prossima volta che il cibo degradi si perda metà delle provviste. Questa azione e sovrapponibile, si possono preaparare più conserve, ogni degrado si attiverà una conserva alla volta", costo: 4, skills: [] },
    { nome: "Corridore", desc: "Ottieni +1 metri di velocità,  la stamina nel muoverti viene consumata a metà.", costo: 4, skills: [] },
    {nome:"Cuoco Miserabile",desc:"Puoi spendere 2 ore per trasformare 15 unità di cibo avariato in 1 unità di cibo sano",costo:4,skills:[]},
    { nome: "Digiuno", desc: "Richiedi 20% meno cibo", costo: 4, skills: [] },
    { nome: "Orrecchio Fino", desc: "Hai vantaggio nelle prove per l'udito, +2 a percezione e senti piu' chiaramente", costo: 2, skills: [] },
    { nome: "Ottimo cuoco", desc: "Cucinando rendi il cibo più nutriente del 20%. Il tempo di cucina deve essere almeno di un’ora per 4 porzioni.", costo: 5, skills: [] },
    { nome: "Raccattatore", desc: "Quando ricerchi il tiro per decidere il loot nella struttura aumenta di 2.", costo: 12, skills: [] },
    { nome: "Razionamento", desc: "Ogni 15 risorse tra acqua e cibo consumate nel magazzino(compresi i piatti deliziosi), ottieni senza consumare niente il riempimento delle barre di fame e sete di 0.25 (non applica appena nutrito o appena dissetato)", costo: 6, skills: [] },
    { nome: "Rigenerazione molto veloce", desc: "La rigenerazione dei punti ferita reali è ridotta di un quarto", costo: 6, skills: [] },
    { nome: "Sonno leggero", desc: "Ti svegli molto facilmente. Non ti perdi nulla mentre dormi", costo: 2, skills: [] },
    { nome: "Stomaco di ferro", desc: "Ti nutri del doppio quando mangi cibo avariato e +2 ai tiri per essere ammalato da esso", costo: 2, skills: [] },
    { nome: "Stress fisico", desc: "Puoi ridurre la tua fatica di 2 infliggendo un danno nei punti ferita reali. Questo perk non è usabile se sei nello stato A Rischio Di Funzionalità.", costo: 5, skills: [] },
    { nome: "Veglia eterna", desc: "ll malus del primo stadio di insonnia è dimezzato.  Se vieni attaccato durante un riposo, la tua iniziativa aumenta automaticamente di +5.", costo: 4, skills: [] },
    { nome: "Animale notturno", desc: "Durante il giorno ottieni svantaggio nelle prove di Percezione e la tua percezione passiva scende di 4. Durante la notte riesci a vedere nel buio intorno a te di 3 metri.", costo: -3, skills: [] },
    { nome: "Bocca asciutta", desc: "Richiedi 20% più acqua", costo: -5, skills: [] },
    { nome: "Insaziabile", desc: "Richiedi 20% più cibo", costo: -4, skills: [] },
    { nome: "Notveole", desc: "Nemici hanno di +2 Percezione Passiva e Percezione per trovarti", costo: -2, skills: [] },
    { nome: "Pessimo orientamento", desc: "Quando il tuo personaggio va ad esplorare da solo ha la probabilità del 70% di perdersi o non ricordare gli edifici che ha esplorato/scoperto. Questo effetto e' possibile anche se le persone con lui hanno Pessimo Orientamento.", costo: -3, skills: [] },
    { nome: "Stomaco sensibile", desc: "Vulnerabile a cibi avariati / cattiva nutrizione", costo: -2, skills: [] },
    { nome: "Insonne", desc: "Ti nutri della metà quando mangi cibo avariato e -2 ai tiri per essere ammalato da esso", costo: -4, skills: [] },
    { nome: "Russare", desc: "Russi molto forte. Le persone che dormono nella tua stanza hanno la probabilità del 30% di ridurre il loro riposo del 50%. Questa percentuale è 0% se hanno Sonno Pesante e 100% se hanno Sonno Leggero  ", costo: -3, skills: [] },
    { nome: "Schizzonoso", desc: "La tua Follia aumenta del doppio se mangi cibo avariato o non convenzionale", costo: -2, skills: [] },
    { nome: "Sonno pesante", desc: "Ti svegli molto difficilmente, quando dormi è più facile che sei vittima di imboscata e non senti nulla.", costo: -2, skills: [] },   
    ],
    "studio": [
    { nome: "Apprendimento eccezionale", desc: "Ottieni +3 ai tiri per apprendimento", costo: 8, skills: [] },
    { nome: "Apprendistato eccezionale", desc: "Ottieni il doppio dei punti Artificeria (sia AG che PS) quando aiuti qualcuno a montare qualcosa", costo: 4, skills: [] },
    {nome:"Comunità medica",desc:"Quando agisci come Assistente in un'operazione medica, riduci la CD di un ulteriore -2 (totale -4) e il Leader consuma la metà dei materiali avanzati richiesti.",costo:4,skills:[],requires:"Medicina Livello 1"},
    { nome: "Medico sprovveduto", desc: "Riduci della metà l'uso dei materiali base per ogni tua operazione di  ma il CD della cura aumenta di 2.", costo: 5, skills: [], requires:"Medicina Livello 2"},
    {nome:"Nessuno muore sotto le mie mani",desc:"Se stai curando un paziente in fin di morte o provando a rianimarlo o curare l'ultimo stadio di malattia puoi spendere 1 materiale critico per avere una diagnosi certa opphre +4 al tiro per la medicazione",costo: 3,skills:[],requires:"Medicina Livello 2"},
    { nome: "Studio in compagnia", desc: "Se un'altra creatura sta studiando/imparando con te ottieni +2 nel tiro per imparare (incluso l'insegnante)", costo: 5, skills: [] },
    { nome: "Insegnante", desc: "Quando insegni una competenza a una creatura essa ottiene +1d6 al tiro per apprendere", costo: 6, skills: [] },
    { nome: "Riciclatore disperato", desc: "Ottieni il 20% di materiali quando smonti un oggetto. E quando operi/crei un composto usi il 10% in meno delle risorse.", costo: 6, skills: [] },
    { nome: "Analfabeta", desc: "Non sai leggere. ", costo: -12, skills: [] },
    {nome: "Deconcentrato", desc: "Se studi/lavori per più di tre ore senza pause il tempo di studio lavoro aumenta del 30%.", costo: -3, skills: [] },
    {nome: "Ignorante", desc: "Ottieni svantaggio in una competenza a tua scelta (Arcano, Artificeria, Medicina, Natura, Storia, Religione,Sopravivenza,Cucina) (Accumulabile per diverse competenze)", costo: -2, skills: [],repeats: true},
    { nome: "Maldestro", desc: "Ottieni svantaggio nelle prove di Manodopera, Rapidità di mano e Artiferia. Per imparare queste materie richiedi il 30% in piu' del tempo.", costo: -5, skills: [] },
    { nome: "Pessimo studente", desc: "Richiedi 1/3 delle ore in più di studio per migliorare il tuo dado di apprendimento", costo: -7, skills: [] },
    ],
    "medicina": [
        { nome: "Medicina Livello 1", desc: "Conoscenze di base medicina.", costo: 4, skills: ['Medicina'] },
        { nome: "Medicina Livello 2", desc: "Conoscenze intermedie medicina.", costo: 6, skills: ['Medicina'], requires: 'Medicina Livello 1' },
        { nome: "Medicina Livello 3", desc: "Conoscenze avanzate medicina.", costo: 9, skills: ['Medicina'], requires: 'Medicina Livello 2' },
        { nome: "Medicina Livello 4", desc: "Conoscenze esperte medicina.", costo: 12, skills: ['Medicina'], requires: 'Medicina Livello 3' },
        { nome: "Medicina Livello 5", desc: "Conoscenze da chirurgo rianimatore.", costo: 15, skills: ['Medicina'], requires: 'Medicina Livello 4' }
    ]
};