// perks.js

const DATABASE_PERK = {
    "competenze base": [
        { nome: "Acrobata", desc: "Competenza in Atletica e Acrobazia", costo: 4, skills: ["Atletica", "Acrobazia"] },
        { nome: "Addestratore da circo", desc: "Competenza in Addestrare animali e Intrattenere", costo: 3, skills: ["Addestrare animali", "Intrattenere"] },
        { nome: "Allevatore", desc: "Competenza in Addestrare animali e Manodopera", costo: 3, skills: ["Addestrare animali", "Manodopera"] },
        { nome: "Ambasciatore", desc: "Competenza in Storia e Persuasione", costo: 3, skills: ["Storia", "Persuasione"] },
        { nome: "Appassionato della natura", desc: "Competenza in Natura e Addestrare gli animali", costo: 2, skills: ["Natura", "Addestrare gli animali"] },
        { nome: "Artigiano Arcano", desc: "Competenza in Manodopera e Arcano", costo: 3, skills: ["Manodopera", "Arcano"] },
        { nome: "Artista accademico", desc: "Competenza in Storia e Intrattenere", costo: 2, skills: ["Storia", "Intrattenere"] },
        { nome: "Ballerina", desc: "Competenza in Intrattenere e Acrobazia", costo: 3, skills: ["Intrattenere", "Acrobazia"] },
        { nome: "Borseggiatore", desc: "Competenza in Rapidità di mano e Acrobazia", costo: 4, skills: ["Rapidità di mano", "Acrobazia"] },
        { nome: "Bruto", desc: "Competenza in Atletica e Intimidire", costo: 3, skills: ["Atletica", "Intimidire"] },
        { nome: "Cacciatore", desc: "Competenza in Sopravvivenza e Percezione", costo: 4, skills: ["Sopravvivenza", "Percezione"] },
        { nome: "Casalingo", desc: "Competenza in Manodopera e Cucina", costo: 3, skills: ["Manodopera", "Cucina"] },
        { nome: "Cuoco", desc: "Competenza in Natura e Cucina", costo: 3, skills: ["Natura", "Cucina"] },
        { nome: "Detective", desc: "Competenza in Indagare e Intuizione", costo: 3, skills: ["Indagare", "Intuizione"] },
        { nome: "Escursionista", desc: "Competenza in Sopravvivenza e Cucina", costo: 3, skills: ["Sopravvivenza", "Cucina"] },
        { nome: "Esperto di Sopravvivenza", desc: "Competenza in Natura e Sopravvivenza", costo: 4, skills: ["Natura", "Sopravvivenza"] },
        { nome: "Esploratore di Rovine", desc: "Competenza in Storia e Acrobazia", costo: 3, skills: ["Storia", "Acrobazia"] },
        { nome: "Fuggiasco", desc: "Competenza in Rapidità di mano e Furtività", costo: 4, skills: ["Rapidità di mano", "Furtività"] },
        { nome: "Infiltrato", desc: "Competenza in Furtività e Inganno", costo: 6, skills: ["Furtività", "Inganno"] },
        { nome: "Ladro", desc: "Competenza in Furtività e Strumenti da scasso", costo: 5, skills: ["Furtività", "Strumenti da scasso"] },
        { nome: "Mago", desc: "Competenza in Arcano e Intuizione", costo: 4, skills: ["Arcano", "Intuizione"] },
        { nome: "Missionario", desc: "Competenza in Atletica e Religione", costo: 4, skills: ["Atletica", "Religione"] },
        { nome: "Pastore", desc: "Competenza in Persuasione e Religione", costo: 3, skills: ["Persuasione", "Religione"] },
        { nome: "Poker Face", desc: "Competenza in Inganno e Giochi di carte", costo: 3, skills: ["Inganno", "Giochi di carte"] },
        { nome: "Predicatore", desc: "Competenza in Religione e Intimidire", costo: 3, skills: ["Religione", "Intimidire"] },
        { nome: "Prestigiatore", desc: "Competenza in Rapidità di mano e Persuasione", costo: 4, skills: ["Rapidità di mano", "Persuasione"] },
        { nome: "Oracolo", desc: "Competenza in Percezione e Arcano", costo: 4, skills: ["Percezione", "Arcano"] },
        { nome: "Oratore", desc: "Competenza in Intuizione e Intrattenere", costo: 4, skills: ["Intuizione", "Intrattenere"] },
        { nome: "Ricattatore", desc: "Competenza in Investigare e Intimidire", costo: 4, skills: ["Investigare", "Intimidire"] },
        { nome: "Ricercatore magico", desc: "Competenza in Arcano e Investigare", costo: 4, skills: ["Arcano", "Investigare"] },
        { nome: "Scassinatore", desc: "Competenza in Percezione e Strumenti da scasso", costo: 4, skills: ["Percezione", "Strumenti da scasso"] },
        { nome: "Selvaggio", desc: "Competenza in Addestrare Animali e Atletica", costo: 4, skills: ["Addestrare Animali", "Atletica"] },
        { nome: "Spia", desc: "Competenza in Furtività e Indagare", costo: 5, skills: ["Furtività", "Indagare"] },
        { nome: "Storico", desc: "Competenza in Storia e Arcano", costo: 3, skills: ["Storia", "Arcano"] },
        { nome: "Taverniere", desc: "Competenza in Cucina e Giochi di Carte", costo: 3, skills: ["Cucina", "Giochi di Carte"] },
        { nome: "Truffatore", desc: "Competenza in Inganno e Intuizione", costo: 3, skills: ["Inganno", "Intuizione"] },
        { nome: "Tuttofare", desc: "Competenza in Manodopera e Strumenti da Scasso", costo: 3, skills: ["Manodopera", "Strumenti da Scasso"] },
        { nome: "Voce del popolo", desc: "Competenza in Inganno e Persuasione", costo: 3, skills: ["Inganno", "Persuasione"] }
    ],
    // Categorie pronte per aggiornamenti futuri
    "background": [],
    "carisma e sociale": [],
    "combattimento": [],
    "fisico e salute": [],
    "magici": [],
    "razziali": [],
    "sopravvivenza": [],
    "studio": []
};