// perks.js

const DATABASE_PERK = {
    "competenze base": [
        { nome: "Acrobata", desc: "Competenza in Atletica e Acrobazia", costo: 4, skills: ["Atletica", "Acrobazia"] },
        { nome: "Addestratore da circo", desc: "Competenza in Addestrare animali e Intrattenere", costo: 3, skills: ["Addestrare animali", "Intrattenere"] },
        { nome: "Allevatore", desc: "Competenza in Addestrare animali e Manodopera", costo: 3, skills: ["Addestrare animali", "Manodopera"] },
        { nome: "Ambasciatore", desc: "Competenza in Storia e Persuasione", costo: 3, skills: ["Storia", "Persuasione"] },
        { nome: "Appassionato della natura", desc: "Competenza in Natura e Addestrare gli animali", costo: 2, skills: ["Natura", "Addestrare gli animali"] },
        { nome: "Artigiano Arcano", desc: "Competenza in Manodopera e Arcano", costo: 3, skills: ["Manodopera", "Arcano"] },
        { nome: "Artista accademico", desc: "Competenza in Storia e Intrattenere", costo: 2, skills: ["Storia", "Intrattenere"] },
        { nome: "Ballerina", desc: "Competenza in Intrattenere e Acrobazia", costo: 3, skills: ["Intrattenere", "Acrobazia"] },
        { nome: "Borseggiatore", desc: "Competenza in Rapidità di mano e Acrobazia", costo: 5, skills: ["Rapidità di mano", "Acrobazia"] },
        { nome: "Bruto", desc: "Competenza in Atletica e Intimidire", costo: 3, skills: ["Atletica", "Intimidire"] },
        { nome: "Cacciatore", desc: "Competenza in Sopravvivenza e Percezione", costo: 4, skills: ["Sopravvivenza", "Percezione"] },
        { nome: "Casalingo", desc: "Competenza in Manodopera e Cucina", costo: 4, skills: ["Manodopera", "Cucina"] },
        { nome: "Cuoco", desc: "Competenza in Natura e Cucina", costo: 4, skills: ["Natura", "Cucina"] },
        { nome: "Detective", desc: "Competenza in Indagare e Intuizione", costo: 3, skills: ["Indagare", "Intuizione"] },
        { nome: "Escursionista", desc: "Competenza in Sopravvivenza e Cucina", costo: 3, skills: ["Sopravvivenza", "Cucina"] },
        { nome: "Esperto di Sopravvivenza", desc: "Competenza in Natura e Sopravvivenza", costo: 4, skills: ["Natura", "Sopravvivenza"] },
        { nome: "Esploratore di Rovine", desc: "Competenza in Storia e Acrobazia", costo: 3, skills: ["Storia", "Acrobazia"] },
        { nome: "Fuggiasco", desc: "Competenza in Rapidità di mano e Furtività", costo: 4, skills: ["Rapidità di mano", "Furtività"] },
        { nome: "Infiltrato", desc: "Competenza in Furtività e Inganno", costo: 5, skills: ["Furtività", "Inganno"] },
        { nome: "Ladro", desc: "Competenza in Furtività e Strumenti da scasso", costo: 6, skills: ["Furtività", "Strumenti da scasso"] },
        { nome: "Mago", desc: "Competenza in Arcano e Intuizione", costo: 3, skills: ["Arcano", "Intuizione"] },
        { nome: "Missionario", desc: "Competenza in Atletica e Religione", costo: 4, skills: ["Atletica", "Religione"] },
        { nome: "Pastore", desc: "Competenza in Persuasione e Religione", costo: 3, skills: ["Persuasione", "Religione"] },
        { nome: "Poker Face", desc: "Competenza in Inganno e Giochi di carte", costo: 3, skills: ["Inganno", "Giochi di carte"] },
        { nome: "Predicatore", desc: "Competenza in Religione e Intimidire", costo: 3, skills: ["Religione", "Intimidire"] },
        { nome: "Prestigiatore", desc: "Competenza in Rapidità di mano e Persuasione", costo: 4, skills: ["Rapidità di mano", "Persuasione"] },
        { nome: "Oracolo", desc: "Competenza in Percezione e Arcano", costo: 4, skills: ["Percezione", "Arcano"] },
        { nome: "Oratore", desc: "Competenza in Intuizione e Intrattenere", costo: 4, skills: ["Intuizione", "Intrattenere"] },
        { nome: "Ricattatore", desc: "Competenza in Investigare e Intimidire", costo: 4, skills: ["Investigare", "Intimidire"] },
        { nome: "Ricercatore magico", desc: "Competenza in Arcano e Investigare", costo: 4, skills: ["Arcano", "Investigare"] },
        { nome: "Scassinatore", desc: "Competenza in Percezione e Strumenti da scasso", costo: 5, skills: ["Percezione", "Strumenti da scasso"] },
        { nome: "Selvaggio", desc: "Competenza in Addestrare Animali e Atletica", costo: 4, skills: ["Addestrare Animali", "Atletica"] },
        { nome: "Spia", desc: "Competenza in Furtività e Indagare", costo: 5, skills: ["Furtività", "Indagare"] },
        { nome: "Storico", desc: "Competenza in Storia e Arcano", costo: 3, skills: ["Storia", "Arcano"] },
        { nome: "Taverniere", desc: "Competenza in Cucina e Giochi di Carte", costo: 3, skills: ["Cucina", "Giochi di Carte"] },
        { nome: "Truffatore", desc: "Competenza in Inganno e Intuizione", costo: 3, skills: ["Inganno", "Intuizione"] },
        { nome: "Tuttofare", desc: "Competenza in Manodopera e Strumenti da Scasso", costo: 4, skills: ["Manodopera", "Strumenti da Scasso"] },
        { nome: "Voce del popolo", desc: "Competenza in Inganno e Persuasione", costo: 2, skills: ["Inganno", "Persuasione"] }
    ],
    // Categorie pronte per aggiornamenti futuri
    "background": [],
    "carisma e sociale": [
        { nome: "Amicizia", desc: "(Richiede un altro personaggio che abbia questo perk abbinato al tuo) Come reazione se il tuo amico è nel raggio di tre metri, puoi aumentare la sua CA di 2.", costo: 2, skills: [] },
        { nome: "Artista", desc: "Durante il tempo alla base puoi intrattenere gli altri, riducendo la Follia. Ottieni competenza in Intrattenere.", costo: 2, skills: ["Intrattenere"] },
        { nome: "Bel viso", desc: "Ottieni +1 a Carisma e +2 a Intrattenere.", costo: 2, skills: [] },
        { nome: "Guida", desc: "Se un alleato sta facendo nel raggio di 3 metri una prova abilità/usando oggetti in cui tu hai competenza, puoi dargli un bonus di 1d6 (deve poterti vedere/ascoltare).", costo: 3, skills: [] },
        { nome: "Uniti siamo più forti", desc: "Se nel raggio di 3 metri ci sono almeno 2 alleati, tutti ottenete PF fortuna temporanei pari al modificatore di Carisma. Attivabile una volta a battaglia.", costo: 3, skills: [] },
        { nome: "Leader nato", desc: "Ottieni +1 al modificatore Carisma per due membri del party che ti accompagnano (fino a +3).", costo: 3, skills: [] },
        { nome: "Mente ferrea", desc: "Quando vai nel panico puoi usare subito una reazione per usare Pulizia Mentale e rimuoverlo ottenendo +2. Attiva una volta per sessione.", costo: 4, skills: [] },
        { nome: "Seduttore", desc: "Ottieni vantaggio nelle prove Carisma contro un sesso a tua scelta.", costo: 4, skills: [] },
        { nome: "Solitario", desc: "Se sei da solo ottieni +2 a tutte le prove abilità/competenze e migliori risultati nelle esplorazioni.", costo: 2, skills: [] },
        { nome: "Vendicativo", desc: "Quando un tuo alleato subisce un danno reale, ottieni vantaggio negli attacchi verso chi l'ha ferito finché non lo colpisci due volte.", costo: 4, skills: [] },
        { nome: "Vicinanza", desc: "Quando un alleato sta venendo curato o deve fare un TS, puoi usare una reazione per ridurre la CD della prova in base al tuo modificatore di Carisma. Usi a riposo lungo pari al modificatore di Carisma.", costo: 5, skills: [] },
        { nome: "Voce calma", desc: "Ottieni competenza in Persuasione. Quando un alleato è spaventato/affascinato/panico puoi usare reazione/azione bonus per un tiro di Persuasione per rimuovere l'effetto se superi la CD.", costo: 3, skills: ["Persuasione"] }
    ],
    "combattimento": [
        { nome: "Arti marziali", desc: "Usi Destrezza per colpire e danni con mani nude. Se il bersaglio fallisce un attacco corpo a corpo, puoi costringerlo a un TS su Forza (CD 8 + Destrezza + competenza) per disarmarlo o atterrarlo.", costo: 6, skills: [] },
        { nome: "Assassino sprecato", desc: "Quando sorprendi un nemico in combattimento ottieni +1d6 danno extra.", costo: 4, skills: [] },
        { nome: "Assetato di adrenalina", desc: "Colpire un nemico ti dà +1 al prossimo tiro per colpire, fino a +3. L’effetto si resetta se manchi o non colpisci per un turno.", costo: 3, skills: [] },
        { nome: "Colpisci e fuggi", desc: "Puoi attaccare un nemico mentre ti muovi e attraversare il suo spazio; il danno subisce -2.", costo: 4, skills: [] },
        { nome: "Colpo pesante", desc: "Dopo un colpo riuscito puoi usare un’azione bonus per rallentare il bersaglio di 3 metri.", costo: 3, skills: [] },
        { nome: "Colpo alla testa", desc: "Critico a distanza +2d6 danno. Scegli un numero fortunato all’inizio della campagna; quel tiro diventa critico.", costo: 7, skills: [] },
        { nome: "Concentrazione ferrea", desc: "Hai vantaggio nelle prove per non perdere la concentrazione.", costo: 2, skills: [] },
        { nome: "Contro un esercito", desc: "Se sei circondato da almeno 2 nemici in mischia, ottieni +1d6 danno.", costo: 2, skills: [] },
        { nome: "Cura delle armi", desc: "Ottieni +2 ai tiri per colpire con la stessa arma dopo 3 combattimenti, se hai almeno competenza 3 con quell’arma.", costo: 5, skills: [] },
        { nome: "Duellante", desc: "Se attacchi un solo avversario, ottieni 5 PF fortuna temporanei usabili solo contro quel nemico.", costo: 2, skills: [] },
        { nome: "Esecutore", desc: "Quando un nemico è sotto la sua vita, puoi usare un’azione bonus per +2d4 danno da mischia, volte al giorno pari al modificatore di Forza.", costo: 3, skills: [] },
        { nome: "Fino all'ultimo", desc: "Ignori gli effetti delle ferite reali fino a fine scontro. Le ferite attuali hanno il 40% di probabilità di peggiorare di grado.", costo: 6, skills: [] },
        { nome: "Fuggi", desc: "Appena entri in combattimento puoi usare un’azione bonus per Scatto o Disimpegno (2/giorno).", costo: 3, skills: [] },
        { nome: "Lotta", desc: "Entri in furia per 1 min, ottieni bonus competenza ai colpi ma perdi concentrazione se non attacchi per un turno (2/giorno).", costo: 4, skills: [] },
        { nome: "Impassibile", desc: "Rimanendo fermo per un turno ottieni +2 CA.", costo: 2, skills: [] },
        { nome: "Guerriero", desc: "+5 PF fortuna massimi. Due volte al giorno puoi rigenerare 1d4 + mod Costituzione con un’azione in combattimento.", costo: 6, skills: [] },
        { nome: "Mani nude 1", desc: "Aumenti il danno da colpi senza armi a 1d4 + mod Forza.", costo: 2, skills: [] },
        { nome: "Mani nude 2", desc: "Aumenti il danno da colpi senza armi a 1d6 + mod Forza.", costo: 4, skills: [], requires: "Mani nude 1" },
        { nome: "Mani nude 3", desc: "Aumenti il danno da colpi senza armi a 1d8 + mod Forza.", costo: 6, skills: [], requires: "Mani nude 2" },
        { nome: "Memento Mori", desc: "Sotto 1/3 PF fortuna puoi abbassare la CA di 2 per vantaggio agli attacchi per 1 min (richiede concentrazione, 1/giorno).", costo: 4, skills: [] },
        { nome: "Muro di Carne", desc: "Quando proteggi un alleato e l’attacco colpisce, puoi subire tu il danno ridotto del tuo mod Costituzione.", costo: 5, skills: [] },
        { nome: "Nato per combattere", desc: "Rigeneri 1d6 + mod Destrezza PF fortuna all’inizio del combattimento.", costo: 6, skills: [] },
        { nome: "Ottima mira", desc: "+1 ai colpi e danni con armi a distanza se hai competenza di livello 2 con quell’arma.", costo: 5, skills: [] },
        { nome: "Scatto Reattivo", desc: "Con Bloccare, se il nemico fallisce il TS, ottieni un attacco in mischia gratuito con danno dimezzato.", costo: 4, skills: [] },
        { nome: "Scivolata", desc: "Mentre ti muovi e subisci un attacco di opportunità, puoi usare la reazione per schivarlo automaticamente.", costo: 4, skills: [] },
        { nome: "Sempre pronto", desc: "Entri automaticamente primo in combattimento (2/giorno).", costo: 3, skills: [] },
        { nome: "Sorte improvvisa", desc: "Scegli 4 numeri. Se tiri uno di questi, il colpo è critico. I 2 successivi attacchi contro di te hanno vantaggio. Uso al giorno pari al mod Saggezza.", costo: 4, skills: [] },
        { nome: "Esitazione", desc: "All’inizio del combattimento non puoi usare reazioni e perdi 3 metri di velocità nel primo turno.", costo: -5, skills: [] },
        { nome: "Pacifista", desc: "I tuoi attacchi infliggono 1d4 danno in meno.", costo: -4, skills: [] },
        { nome: "Paralisi", desc: "Quando finisci PF o subisci 1 PF, fai TS Saggezza 14 o resti stordito un turno. Max 3 volte a sessione.", costo: -6, skills: [] },
        { nome: "Fifone", desc: "Se entri nel raggio d’attacco di un nemico, sei spaventato una sola volta per combattimento.", costo: -4, skills: [] },
        { nome: "Gambe pesanti", desc: "Immediatamente davanti al pericolo perdi metà della velocità per un turno.", costo: -4, skills: [] },
        { nome: "Mani di burro", desc: "Quando vieni attaccato, fai TS Costituzione 10 o l’arma cade e serve un’azione per riprenderla.", costo: -4, skills: [] },
        { nome: "Scoordinato", desc: "Muovendoti e incontrando un ostacolo hai il 50% di cadere.", costo: -4, skills: [] },
        { nome: "Troppo entusiasta", desc: "-2 CA, se fallisci un attacco il nemico ottiene +2 al prossimo tiro contro di te, ma tu ottieni +2 ai tuoi tiri per colpire.", costo: -7, skills: [] }
    ],
    "fisico e salute": [],
    "background": [
        { nome: "Abbandono", desc: "Vai nel panico se rimani da solo per più di un'ora.", costo: -3, skills: [] },
        { nome: "Balbuzziente", desc: "Balbuzie o accento insolito: ottieni svantaggio nelle prove Intimidire e Inganno.", costo: -2, skills: [] },
        { nome: "Cicatrici", desc: "Ottieni competenza in Intimidire ma -3 alle altre prove di Carisma.", costo: -3, skills: ["Intimidire"] },
        { nome: "Codice Etico", desc: "Possiedi un codice morale/legale rigido. Quando compi un'azione ritenuta immorale subisci -2 ai tiri di Carisma per 24 ore.", costo: -3, skills: [] },
        { nome: "CroceRossina", desc: "Se non aiuti un compagno ferito ottieni sensi di colpa che aumentano la Follia e danno il perk Insonne. Gli effetti si possono sovrapporre fino a 4 volte.", costo: -5, skills: [] },
        { nome: "Imbarazzo", desc: "Quando fallisci una prova di Carisma su una persona, avrai svantaggio su prove di Carisma su di lei e -1 ai tiri abilità se la persona è nel raggio di vista.", costo: -4, skills: [] },
        { nome: "Introversione", desc: "Ottieni svantaggio nelle prove di Carisma.", costo: -4, skills: [] },
        { nome: "Misogino/Androgeno", desc: "Ottieni svantaggio nelle prove di Carisma sul sesso opposto.", costo: -3, skills: [] },
        { nome: "Panico Sociale", desc: "Se sei in presenza di più di quattro persone ottieni svantaggio nelle prove di Carisma.", costo: -2, skills: [] },
        { nome: "Paranoico", desc: "Hai una paranoia che richiede comportamenti di evitamento quotidiani; se ignorati vai in panico fino a compiere l'azione.", costo: -4, skills: [] },
        { nome: "Rancoroso", desc: "Quando qualcuno ti fa un torto subisci vari malus: +2 CD alle prove di Medicina se lo curi, -40% velocità studio/creazione lavorando con lui, +4 CD su azioni coordinate.", costo: -5, skills: [] },
        { nome: "Scontroso", desc: "Hai svantaggio su Intuizione, Intrattenere, Persuasione verso persone che non ti piacciono (ogni 5 persone te ne può piacere una).", costo: -2, skills: [] }
        ,{ nome: "Fuori dal mondo", desc: "Perk che ti isola dal linguaggio comune: perdi la lingua Verbum dalle lingue conosciute.", costo: 1, skills: [] },
        { nome: "Armato", desc: "Inizia l'avventura con un'arma a tua scelta in cui hai competenza. Munizioni: 10 per arco/balestra, 3 per pistola.", costo: 3, skills: [] },
        { nome: "Avventuriero", desc: "Inizia con zaino capiente, cibo e acqua per 1 giorno, e sacco a pelo.", costo: 3, skills: [] },
        { nome: "Autoctono", desc: "Possiedi una casa in città; loot casuale deciso dal master.", costo: 8, skills: [] },
        { nome: "Occhi della paura", desc: "Vantaggio su prove abilità e attacchi se sei in stato di Panico.", costo: 6, skills: [] },
        { nome: "Fortunato", desc: "2 gettoni fortuna al giorno utilizzabili per migliorare loot o tirare con vantaggio.", costo: 8, skills: [] },
        { nome: "Lingue", desc: "Conosci una lingua in più; selezionabile. Riacquistabile più volte.", costo: 2, skills: [], repeats: true },
        { nome: "Sadismo", desc: "Ottieni bonus temporanei quando infliggi sofferenza a persone non infette (max 4/giorno).", costo: 3, skills: [] },
        { nome: "Urbex", desc: "Competenza in Acrobazia e vantaggi nell'esplorazione di edifici.", costo: 3, skills: [] },
        { nome: "Armato (malus)", desc: "Malus esempio.", costo: -3, skills: [] }
    ],
    "more_malus": [
        { nome: "Agofobico", desc: "Le prove di medicina per medicarti aumentano di +2 al CD, vai nel panico se vieni a contatto con gli aghi.", costo: 4, skills: [] },
        { nome: "Agorafobico", desc: "Entri in Panico quando sei in spazi molto aperti.", costo: 3, skills: [] },
        { nome: "Alcolista", desc: "Senza alcool per troppo tempo ottieni un debuff -2 ad ogni tiro abilità.", costo: 3, skills: [] },
        { nome: "Claustrofobico", desc: "Entri in Panico quando sei in spazi chiusi.", costo: 2, skills: [] },
        { nome: "Cleptomane", desc: "Quando entri in una nuova zona devi prendere qualcosa. Se non lo fai aumenta la Follia e avrai -2 a Percezione, Intuizione, Indagare finché non riesci a tornare per prendere qualcosa.", costo: 4, skills: [] },
        { nome: "Emofobico", desc: "Entri in Panico se entri in contatto col sangue oppure c’è troppo sangue intorno.", costo: 4, skills: [] },
        { nome: "Insettofobia", desc: "Vai nel panico alla presenza di grandi quantità di insetti o insetti giganti; ottieni -2 a Carisma vicino a persone con tratti da insetto.", costo: 2, skills: [] },
        { nome: "Paura del buio", desc: "Vai nel panico al buio e di notte se sei fuori casa.", costo: 5, skills: [] },
        { nome: "Pessimista", desc: "Quando fallisci una prova o attacco ottieni un -1 alla prova successiva, effetto sovrapponibile fino a -5.", costo: 4, skills: [] },
        { nome: "Sadismo patologico", desc: "Include Sadismo; se non ottieni bonus da Sadismo per troppo tempo ottieni svantaggio in Intelligenza/Carisma/Saggezza e la Follia aumenta.", costo: 6, skills: [] },
        { nome: "Sensibile", desc: "Se qualcuno vicino a te ha Panico, hai il 30% di ottenerlo anche tu. Effetto sovrapponibile.", costo: 2, skills: [] },
        { nome: "Sfortunato", desc: "Due volte a sessione il master può obbligarti a fare un tiro con svantaggio.", costo: 6, skills: [] },
        { nome: "Traumafobia", desc: "Entri in Panico se perdi un punto vita reale.", costo: 2, skills: [] },
        { nome: "Tumore magico", desc: "Il tuo personaggio non supererà i 7 giorni. Dal giorno 5 ottieni -1d6 a ogni tiro per colpire; giorno 6 due stadi di fatica; giorno 7 morirai.", costo: 6, skills: [] },
        { nome: "Vertigini", desc: "Entri in Panico se sei ad alte altezze.", costo: 3, skills: [] },
        { nome: "Hai qualcosa nell'occhio", desc: "Perk unico: solo un personaggio può averlo per campagna.", costo: 20, skills: [] },
        { nome: "Nascita straordinaria", desc: "Perk unico: solo un personaggio può averlo per campagna.", costo: 20, skills: [] }
    ],
    "magici": [],
    "razziali": [],
    "sopravvivenza": [],
    "studio": [
        { nome: "Insegnante", desc: "Hai esperienza didattica: ottieni vantaggio sui tiri di apprendimento dallo studio.", costo: 8, skills: [] }
    ],
    "medicina": [
        { nome: "Medicina Livello 1", desc: "Conoscenze di base medicina.", costo: 4, skills: ['Medicina'] },
        { nome: "Medicina Livello 2", desc: "Conoscenze intermedie medicina.", costo: 6, skills: ['Medicina'], requires: 'Medicina Livello 1' },
        { nome: "Medicina Livello 3", desc: "Conoscenze avanzate medicina.", costo: 9, skills: ['Medicina'], requires: 'Medicina Livello 2' },
        { nome: "Medicina Livello 4", desc: "Conoscenze esperte medicina.", costo: 12, skills: ['Medicina'], requires: 'Medicina Livello 3' },
        { nome: "Medicina Livello 5", desc: "Conoscenze da chirurgo rianimatore.", costo: 15, skills: ['Medicina'], requires: 'Medicina Livello 4' }
    ]
};