PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS utenti (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'giocatore',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS personaggi (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    nome TEXT NOT NULL,
    stamina INTEGER NOT NULL DEFAULT 100,
    hunger INTEGER NOT NULL DEFAULT 100,
    thirst INTEGER NOT NULL DEFAULT 100,
    sleep INTEGER NOT NULL DEFAULT 100,
    status TEXT NOT NULL DEFAULT 'attivo',
    data TEXT NOT NULL DEFAULT '{}',
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES utenti(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS proposte (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    nome TEXT NOT NULL,
    descrizione TEXT NOT NULL,
    stato TEXT NOT NULL DEFAULT 'in_attesa',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES utenti(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS documenti (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    master_id INTEGER NOT NULL,
    titolo TEXT NOT NULL,
    contenuto TEXT NOT NULL,
    stato TEXT NOT NULL DEFAULT 'aperto',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(master_id) REFERENCES utenti(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stati_alterati (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    personaggio_id INTEGER NOT NULL,
    tipo TEXT NOT NULL,
    valore INTEGER NOT NULL DEFAULT 0,
    fonte TEXT NOT NULL DEFAULT 'sistema',
    applicato_il TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(personaggio_id) REFERENCES personaggi(id) ON DELETE CASCADE
);

